 * Bootstrap v2.0.4
 *
 * Copyright 2012 Twitter, Inc
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Designed and built with all the love in the world @twitter by @mdo and @fat.
 */

.cc article,
.cc aside,
.cc details,
.cc figcaption,
.cc figure,
.cc footer,
.cc header,
.cc hgroup,
.cc nav,
.cc section {
  display: block;
}

.cc audio,
.cc canvas,
.cc video {
  display: inline-block;
  *display: inline;
  *zoom: 1;
}

.cc audio:not([controls]) {
  display: none;
}

.cc html {
  font-size: 100%;
  -webkit-text-size-adjust: 100%;
      -ms-text-size-adjust: 100%;
}

.cc a:focus {
  outline: thin dotted #333;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}

.cc a:hover,
.cc a:active {
  outline: 0;
}

.cc sub,
.cc sup {
  position: relative;
  font-size: 75%;
  line-height: 0;
  vertical-align: baseline;
}

.cc sup {
  top: -0.5em;
}

.cc sub {
  bottom: -0.25em;
}

.cc img {
  max-width: 100%;
  vertical-align: middle;
  border: 0;
  -ms-interpolation-mode: bicubic;
}

.cc #map_canvas img {
  max-width: none;
}

.cc button,
.cc input,
.cc select,
.cc textarea {
  margin: 0;
  font-size: 100%;
  vertical-align: middle;
}

.cc button,
.cc input {
  *overflow: visible;
  line-height: normal;
}

.cc button::-moz-focus-inner,
.cc input::-moz-focus-inner {
  padding: 0;
  border: 0;
}

.cc button,
.cc input[type="button"],
.cc input[type="reset"],
.cc input[type="submit"] {
  cursor: pointer;
  -webkit-appearance: button;
}

.cc input[type="search"] {
  -webkit-box-sizing: content-box;
     -moz-box-sizing: content-box;
          box-sizing: content-box;
  -webkit-appearance: textfield;
}

.cc input[type="search"]::-webkit-search-decoration,
.cc input[type="search"]::-webkit-search-cancel-button {
  -webkit-appearance: none;
}

.cc textarea {
  overflow: auto;
  vertical-align: top;
}

.cc .clearfix {
  *zoom: 1;
}

.cc .clearfix:before,
.cc .clearfix:after {
  display: table;
  content: "";
}

.cc .clearfix:after {
  clear: both;
}

.cc .hide-text {
  font: 0/0 a;
  color: transparent;
  text-shadow: none;
  background-color: transparent;
  border: 0;
}

.cc .input-block-level {
  display: block;
  width: 100%;
  min-height: 28px;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
      -ms-box-sizing: border-box;
          box-sizing: border-box;
}

.cc body {
  margin: 0;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 13px;
  line-height: 18px;
  color: #333333;
  background-color: #ffffff;
}

.cc a {
  color: #0088cc;
  text-decoration: none;
}

.cc a:hover {
  color: #005580;
  text-decoration: underline;
}

.cc .row {
  margin-left: -20px;
  *zoom: 1;
}

.cc .row:before,
.cc .row:after {
  display: table;
  content: "";
}

.cc .row:after {
  clear: both;
}

.cc [class*="span"] {
  float: left;
  margin-left: 20px;
}

.cc .container,
.cc .navbar-fixed-top .container,
.navbar-fixed-bottom .container {
  width: 940px;
}

.cc .span12 {
  width: 940px;
}

.cc .span11 {
  width: 860px;
}

.cc .span10 {
  width: 780px;
}

.cc .span9 {
  width: 700px;
}

.cc .span8 {
  width: 620px;
}

.cc .span7 {
  width: 540px;
}

.cc .span6 {
  width: 460px;
}

.cc .span5 {
  width: 380px;
}

.cc .span4 {
  width: 300px;
}

.cc .span3 {
  width: 220px;
}

.cc .span2 {
  width: 140px;
}

.cc .span1 {
  width: 60px;
}

.cc .offset12 {
  margin-left: 980px;
}

.cc .offset11 {
  margin-left: 900px;
}

.cc .offset10 {
  margin-left: 820px;
}

.cc .offset9 {
  margin-left: 740px;
}

.cc .offset8 {
  margin-left: 660px;
}

.cc .offset7 {
  margin-left: 580px;
}

.cc .offset6 {
  margin-left: 500px;
}

.cc .offset5 {
  margin-left: 420px;
}

.cc .offset4 {
  margin-left: 340px;
}

.cc .offset3 {
  margin-left: 260px;
}

.cc .offset2 {
  margin-left: 180px;
}

.cc .offset1 {
  margin-left: 100px;
}

.cc .row-fluid {
  width: 100%;
  *zoom: 1;
}

.cc .row-fluid:before,
.cc .row-fluid:after {
  display: table;
  content: "";
}

.cc .row-fluid:after {
  clear: both;
}

.cc .row-fluid [class*="span"] {
  display: block;
  float: left;
  width: 100%;
  min-height: 28px;
  margin-left: 2.127659574%;
  *margin-left: 2.0744680846382977%;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
      -ms-box-sizing: border-box;
          box-sizing: border-box;
}

.cc .row-fluid [class*="span"]:first-child {
  margin-left: 0;
}

.cc .row-fluid .span12 {
  width: 99.99999998999999%;
  *width: 99.94680850063828%;
}

.cc .row-fluid .span11 {
  width: 91.489361693%;
  *width: 91.4361702036383%;
}

.cc .row-fluid .span10 {
  width: 82.97872339599999%;
  *width: 82.92553190663828%;
}

.cc .row-fluid .span9 {
  width: 74.468085099%;
  *width: 74.4148936096383%;
}

.cc .row-fluid .span8 {
  width: 65.95744680199999%;
  *width: 65.90425531263828%;
}

.cc .row-fluid .span7 {
  width: 57.446808505%;
  *width: 57.3936170156383%;
}

.cc .row-fluid .span6 {
  width: 48.93617020799999%;
  *width: 48.88297871863829%;
}

.cc .row-fluid .span5 {
  width: 40.425531911%;
  *width: 40.3723404216383%;
}

.cc .row-fluid .span4 {
  width: 31.914893614%;
  *width: 31.8617021246383%;
}

.cc .row-fluid .span3 {
  width: 23.404255317%;
  *width: 23.3510638276383%;
}

.cc .row-fluid .span2 {
  width: 14.89361702%;
  *width: 14.8404255306383%;
}

.cc .row-fluid .span1 {
  width: 6.382978723%;
  *width: 6.329787233638298%;
}

.cc .container {
  margin-right: auto;
  margin-left: auto;
  *zoom: 1;
}

.cc .container:before,
.cc .container:after {
  display: table;
  content: "";
}

.cc .container:after {
  clear: both;
}

.cc .container-fluid {
  padding-right: 20px;
  padding-left: 20px;
  *zoom: 1;
}

.cc .container-fluid:before,
.cc .container-fluid:after {
  display: table;
  content: "";
}

.cc .container-fluid:after {
  clear: both;
}

.cc p {
  margin: 0 0 9px;
}

.cc p small {
  font-size: 11px;
  color: #999999;
}

.cc .lead {
  margin-bottom: 18px;
  font-size: 20px;
  font-weight: 200;
  line-height: 27px;
}

.cc h1,
.cc h2,
.cc h3,
.cc h4,
.cc h5,
.cc h6 {
  margin: 0;
  font-family: inherit;
  font-weight: bold;
  color: inherit;
  text-rendering: optimizelegibility;
}

.cc h1 small,
h2 small,
h3 small,
h4 small,
h5 small,
h6 small {
  font-weight: normal;
  color: #999999;
}

.cc h1 {
  font-size: 30px;
  line-height: 36px;
}

.cc h1 small {
  font-size: 18px;
}

.cc h2 {
  font-size: 24px;
  line-height: 36px;
}

.cc h2 small {
  font-size: 18px;
}

.cc h3 {
  font-size: 18px;
  line-height: 27px;
}

.cc h3 small {
  font-size: 14px;
}

.cc h4,
.cc h5,
.cc h6 {
  line-height: 18px;
}

.cc h4 {
  font-size: 14px;
}

.cc h4 small {
  font-size: 12px;
}

.cc h5 {
  font-size: 12px;
}

.cc h6 {
  font-size: 11px;
  color: #999999;
  text-transform: uppercase;
}

.cc .page-header {
  padding-bottom: 17px;
  margin: 18px 0;
  border-bottom: 1px solid #eeeeee;
}

.cc .page-header h1 {
  line-height: 1;
}

.cc ul,
.cc ol {
  padding: 0;
  margin: 0 0 9px 25px;
}

.cc ul ul,
ul ol,
ol ol,
ol ul {
  margin-bottom: 0;
}

.cc ul {
  list-style: disc;
}

.cc ol {
  list-style: decimal;
}

.cc li {
  line-height: 18px;
}

.cc ul.unstyled,
.cc ol.unstyled {
  margin-left: 0;
  list-style: none;
}

.cc dl {
  margin-bottom: 18px;
}

.cc dt,
.cc dd {
  line-height: 18px;
}

.cc dt {
  font-weight: bold;
  line-height: 17px;
}

.cc dd {
  margin-left: 9px;
}

.cc .dl-horizontal dt {
  float: left;
  width: 120px;
  overflow: hidden;
  clear: left;
  text-align: right;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.cc .dl-horizontal dd {
  margin-left: 130px;
}

.cc hr {
  margin: 18px 0;
  border: 0;
  border-top: 1px solid #eeeeee;
  border-bottom: 1px solid #ffffff;
}

.cc strong {
  font-weight: bold;
}

.cc em {
  font-style: italic;
}

.cc .muted {
  color: #999999;
}

.cc abbr[title] {
  cursor: help;
  border-bottom: 1px dotted #999999;
}

.cc abbr.initialism {
  font-size: 90%;
  text-transform: uppercase;
}

.cc blockquote {
  padding: 0 0 0 15px;
  margin: 0 0 18px;
  border-left: 5px solid #eeeeee;
}

.cc blockquote p {
  margin-bottom: 0;
  font-size: 16px;
  font-weight: 300;
  line-height: 22.5px;
}

.cc blockquote small {
  display: block;
  line-height: 18px;
  color: #999999;
}

.cc blockquote small:before {
  content: '\2014 \00A0';
}

.cc blockquote.pull-right {
  float: right;
  padding-right: 15px;
  padding-left: 0;
  border-right: 5px solid #eeeeee;
  border-left: 0;
}

.cc blockquote.pull-right p,
blockquote.pull-right small {
  text-align: right;
}

.cc q:before,
.cc q:after,
.cc blockquote:before,
.cc blockquote:after {
  content: "";
}

.cc address {
  display: block;
  margin-bottom: 18px;
  font-style: normal;
  line-height: 18px;
}

.cc small {
  font-size: 100%;
}

.cc cite {
  font-style: normal;
}

.cc code,
.cc pre {
  padding: 0 3px 2px;
  font-family: Menlo, Monaco, Consolas, "Courier New", monospace;
  font-size: 12px;
  color: #333333;
  -webkit-border-radius: 3px;
     -moz-border-radius: 3px;
          border-radius: 3px;
}

.cc code {
  padding: 2px 4px;
  color: #d14;
  background-color: #f7f7f9;
  border: 1px solid #e1e1e8;
}

.cc pre {
  display: block;
  padding: 8.5px;
  margin: 0 0 9px;
  font-size: 12.025px;
  line-height: 18px;
  word-break: break-all;
  word-wrap: break-word;
  white-space: pre;
  white-space: pre-wrap;
  background-color: #f5f5f5;
  border: 1px solid #ccc;
  border: 1px solid rgba(0, 0, 0, 0.15);
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
}

.cc pre.prettyprint {
  margin-bottom: 18px;
}

.cc pre code {
  padding: 0;
  color: inherit;
  background-color: transparent;
  border: 0;
}

.cc .pre-scrollable {
  max-height: 340px;
  overflow-y: scroll;
}

.cc form {
  margin: 0 0 18px;
}

.cc fieldset {
  padding: 0;
  margin: 0;
  border: 0;
}

.cc legend {
  display: block;
  width: 100%;
  padding: 0;
  margin-bottom: 27px;
  font-size: 19.5px;
  line-height: 36px;
  color: #333333;
  border: 0;
  border-bottom: 1px solid #e5e5e5;
}

.cc legend small {
  font-size: 13.5px;
  color: #999999;
}

.cc label,
.cc input,
.cc button,
.cc select,
.cc textarea {
  font-size: 13px;
  font-weight: normal;
  line-height: 18px;
}

.cc input,
.cc button,
.cc select,
.cc textarea {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.cc label {
  display: block;
  margin-bottom: 5px;
}

.cc select,
.cc textarea,
.cc input[type="text"],
.cc input[type="password"],
.cc input[type="datetime"],
.cc input[type="datetime-local"],
.cc input[type="date"],
.cc input[type="month"],
.cc input[type="time"],
.cc input[type="week"],
.cc input[type="number"],
.cc input[type="email"],
.cc input[type="url"],
.cc input[type="search"],
.cc input[type="tel"],
.cc input[type="color"],
.cc .uneditable-input {
  display: inline-block;
  height: 18px;
  padding: 4px;
  margin-bottom: 9px;
  font-size: 13px;
  line-height: 18px;
  color: #555555;
}

.cc input,
.cc textarea {
  width: 210px;
}

.cc textarea {
  height: auto;
}

.cc textarea,
.cc input[type="text"],
.cc input[type="password"],
.cc input[type="datetime"],
.cc input[type="datetime-local"],
.cc input[type="date"],
.cc input[type="month"],
.cc input[type="time"],
.cc input[type="week"],
.cc input[type="number"],
.cc input[type="email"],
.cc input[type="url"],
.cc input[type="search"],
.cc input[type="tel"],
.cc input[type="color"],
.cc .uneditable-input {
  background-color: #ffffff;
  border: 1px solid #cccccc;
  -webkit-border-radius: 3px;
     -moz-border-radius: 3px;
          border-radius: 3px;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
     -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  -webkit-transition: border linear 0.2s, box-shadow linear 0.2s;
     -moz-transition: border linear 0.2s, box-shadow linear 0.2s;
      -ms-transition: border linear 0.2s, box-shadow linear 0.2s;
       -o-transition: border linear 0.2s, box-shadow linear 0.2s;
          transition: border linear 0.2s, box-shadow linear 0.2s;
}

.cc textarea:focus,
.cc input[type="text"]:focus,
.cc input[type="password"]:focus,
.cc input[type="datetime"]:focus,
.cc input[type="datetime-local"]:focus,
.cc input[type="date"]:focus,
.cc input[type="month"]:focus,
.cc input[type="time"]:focus,
.cc input[type="week"]:focus,
.cc input[type="number"]:focus,
.cc input[type="email"]:focus,
.cc input[type="url"]:focus,
.cc input[type="search"]:focus,
.cc input[type="tel"]:focus,
.cc input[type="color"]:focus,
.cc .uneditable-input:focus {
  border-color: rgba(82, 168, 236, 0.8);
  outline: 0;
  outline: thin dotted \9;
  /* IE6-9 */

.cc   -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(82, 168, 236, 0.6);
     -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(82, 168, 236, 0.6);
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075), 0 0 8px rgba(82, 168, 236, 0.6);
}

.cc input[type="radio"],
.cc input[type="checkbox"] {
  margin: 3px 0;
  *margin-top: 0;
  /* IE7 */

.cc   line-height: normal;
  cursor: pointer;
}

.cc input[type="submit"],
.cc input[type="reset"],
.cc input[type="button"],
.cc input[type="radio"],
.cc input[type="checkbox"] {
  width: auto;
}

.cc .uneditable-textarea {
  width: auto;
  height: auto;
}

.cc select,
.cc input[type="file"] {
  height: 28px;
  /* In IE7, the height of the select element cannot be changed by height, only font-size */

.cc   *margin-top: 4px;
  /* For IE7, add top margin to align select with labels */

.cc   line-height: 28px;
}

.cc select {
  width: 220px;
  border: 1px solid #bbb;
}

.cc select[multiple],
.cc select[size] {
  height: auto;
}

.cc select:focus,
.cc input[type="file"]:focus,
.cc input[type="radio"]:focus,
.cc input[type="checkbox"]:focus {
  outline: thin dotted #333;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}

.cc .radio,
.cc .checkbox {
  min-height: 18px;
  padding-left: 18px;
}

.cc .radio input[type="radio"],
.checkbox input[type="checkbox"] {
  float: left;
  margin-left: -18px;
}

.cc .controls > .radio:first-child,
.controls > .checkbox:first-child {
  padding-top: 5px;
}

.cc .radio.inline,
.cc .checkbox.inline {
  display: inline-block;
  padding-top: 5px;
  margin-bottom: 0;
  vertical-align: middle;
}

.cc .radio.inline + .radio.inline,
.checkbox.inline + .checkbox.inline {
  margin-left: 10px;
}

.cc .input-mini {
  width: 60px;
}

.cc .input-small {
  width: 90px;
}

.cc .input-medium {
  width: 150px;
}

.cc .input-large {
  width: 210px;
}

.cc .input-xlarge {
  width: 270px;
}

.cc .input-xxlarge {
  width: 530px;
}

.cc input[class*="span"],
.cc select[class*="span"],
.cc textarea[class*="span"],
.cc .uneditable-input[class*="span"],
.cc .row-fluid input[class*="span"],
.row-fluid select[class*="span"],
.row-fluid textarea[class*="span"],
.row-fluid .uneditable-input[class*="span"] {
  float: none;
  margin-left: 0;
}

.cc .input-append input[class*="span"],
.input-append .uneditable-input[class*="span"],
.input-prepend input[class*="span"],
.input-prepend .uneditable-input[class*="span"],
.row-fluid .input-prepend [class*="span"],
.row-fluid .input-append [class*="span"] {
  display: inline-block;
}

.cc input,
.cc textarea,
.cc .uneditable-input {
  margin-left: 0;
}

.cc input.span12,
.cc textarea.span12,
.cc .uneditable-input.span12 {
  width: 930px;
}

.cc input.span11,
.cc textarea.span11,
.cc .uneditable-input.span11 {
  width: 850px;
}

.cc input.span10,
.cc textarea.span10,
.cc .uneditable-input.span10 {
  width: 770px;
}

.cc input.span9,
.cc textarea.span9,
.cc .uneditable-input.span9 {
  width: 690px;
}

.cc input.span8,
.cc textarea.span8,
.cc .uneditable-input.span8 {
  width: 610px;
}

.cc input.span7,
.cc textarea.span7,
.cc .uneditable-input.span7 {
  width: 530px;
}

.cc input.span6,
.cc textarea.span6,
.cc .uneditable-input.span6 {
  width: 450px;
}

.cc input.span5,
.cc textarea.span5,
.cc .uneditable-input.span5 {
  width: 370px;
}

.cc input.span4,
.cc textarea.span4,
.cc .uneditable-input.span4 {
  width: 290px;
}

.cc input.span3,
.cc textarea.span3,
.cc .uneditable-input.span3 {
  width: 210px;
}

.cc input.span2,
.cc textarea.span2,
.cc .uneditable-input.span2 {
  width: 130px;
}

.cc input.span1,
.cc textarea.span1,
.cc .uneditable-input.span1 {
  width: 50px;
}

.cc input[disabled],
.cc select[disabled],
.cc textarea[disabled],
.cc input[readonly],
.cc select[readonly],
.cc textarea[readonly] {
  cursor: not-allowed;
  background-color: #eeeeee;
  border-color: #ddd;
}

.cc input[type="radio"][disabled],
.cc input[type="checkbox"][disabled],
.cc input[type="radio"][readonly],
.cc input[type="checkbox"][readonly] {
  background-color: transparent;
}

.cc .control-group.warning > label,
.control-group.warning .help-block,
.control-group.warning .help-inline {
  color: #c09853;
}

.cc .control-group.warning .checkbox,
.control-group.warning .radio,
.control-group.warning input,
.control-group.warning select,
.control-group.warning textarea {
  color: #c09853;
  border-color: #c09853;
}

.cc .control-group.warning .checkbox:focus,
.control-group.warning .radio:focus,
.control-group.warning input:focus,
.control-group.warning select:focus,
.control-group.warning textarea:focus {
  border-color: #a47e3c;
  -webkit-box-shadow: 0 0 6px #dbc59e;
     -moz-box-shadow: 0 0 6px #dbc59e;
          box-shadow: 0 0 6px #dbc59e;
}

.cc .control-group.warning .input-prepend .add-on,
.control-group.warning .input-append .add-on {
  color: #c09853;
  background-color: #fcf8e3;
  border-color: #c09853;
}

.cc .control-group.error > label,
.control-group.error .help-block,
.control-group.error .help-inline {
  color: #b94a48;
}

.cc .control-group.error .checkbox,
.control-group.error .radio,
.control-group.error input,
.control-group.error select,
.control-group.error textarea {
  color: #b94a48;
  border-color: #b94a48;
}

.cc .control-group.error .checkbox:focus,
.control-group.error .radio:focus,
.control-group.error input:focus,
.control-group.error select:focus,
.control-group.error textarea:focus {
  border-color: #953b39;
  -webkit-box-shadow: 0 0 6px #d59392;
     -moz-box-shadow: 0 0 6px #d59392;
          box-shadow: 0 0 6px #d59392;
}

.cc .control-group.error .input-prepend .add-on,
.control-group.error .input-append .add-on {
  color: #b94a48;
  background-color: #f2dede;
  border-color: #b94a48;
}

.cc .control-group.success > label,
.control-group.success .help-block,
.control-group.success .help-inline {
  color: #468847;
}

.cc .control-group.success .checkbox,
.control-group.success .radio,
.control-group.success input,
.control-group.success select,
.control-group.success textarea {
  color: #468847;
  border-color: #468847;
}

.cc .control-group.success .checkbox:focus,
.control-group.success .radio:focus,
.control-group.success input:focus,
.control-group.success select:focus,
.control-group.success textarea:focus {
  border-color: #356635;
  -webkit-box-shadow: 0 0 6px #7aba7b;
     -moz-box-shadow: 0 0 6px #7aba7b;
          box-shadow: 0 0 6px #7aba7b;
}

.cc .control-group.success .input-prepend .add-on,
.control-group.success .input-append .add-on {
  color: #468847;
  background-color: #dff0d8;
  border-color: #468847;
}

.cc input:focus:required:invalid,
.cc textarea:focus:required:invalid,
.cc select:focus:required:invalid {
  color: #b94a48;
  border-color: #ee5f5b;
}

.cc input:focus:required:invalid:focus,
.cc textarea:focus:required:invalid:focus,
.cc select:focus:required:invalid:focus {
  border-color: #e9322d;
  -webkit-box-shadow: 0 0 6px #f8b9b7;
     -moz-box-shadow: 0 0 6px #f8b9b7;
          box-shadow: 0 0 6px #f8b9b7;
}

.cc .form-actions {
  padding: 17px 20px 18px;
  margin-top: 18px;
  margin-bottom: 18px;
  background-color: #f5f5f5;
  border-top: 1px solid #e5e5e5;
  *zoom: 1;
}

.cc .form-actions:before,
.cc .form-actions:after {
  display: table;
  content: "";
}

.cc .form-actions:after {
  clear: both;
}

.cc .uneditable-input {
  overflow: hidden;
  white-space: nowrap;
  cursor: not-allowed;
  background-color: #ffffff;
  border-color: #eee;
  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.025);
     -moz-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.025);
          box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.025);
}

.cc :-moz-placeholder {
  color: #999999;
}

.cc :-ms-input-placeholder {
  color: #999999;
}

.cc ::-webkit-input-placeholder {
  color: #999999;
}

.cc .help-block,
.cc .help-inline {
  color: #555555;
}

.cc .help-block {
  display: block;
  margin-bottom: 9px;
}

.cc .help-inline {
  display: inline-block;
  *display: inline;
  padding-left: 5px;
  vertical-align: middle;
  *zoom: 1;
}

.cc .input-prepend,
.cc .input-append {
  margin-bottom: 5px;
}

.cc .input-prepend input,
.input-append input,
.input-prepend select,
.input-append select,
.input-prepend .uneditable-input,
.input-append .uneditable-input {
  position: relative;
  margin-bottom: 0;
  *margin-left: 0;
  vertical-align: middle;
  -webkit-border-radius: 0 3px 3px 0;
     -moz-border-radius: 0 3px 3px 0;
          border-radius: 0 3px 3px 0;
}

.cc .input-prepend input:focus,
.input-append input:focus,
.input-prepend select:focus,
.input-append select:focus,
.input-prepend .uneditable-input:focus,
.input-append .uneditable-input:focus {
  z-index: 2;
}

.cc .input-prepend .uneditable-input,
.input-append .uneditable-input {
  border-left-color: #ccc;
}

.cc .input-prepend .add-on,
.input-append .add-on {
  display: inline-block;
  width: auto;
  height: 18px;
  min-width: 16px;
  padding: 4px 5px;
  font-weight: normal;
  line-height: 18px;
  text-align: center;
  text-shadow: 0 1px 0 #ffffff;
  vertical-align: middle;
  background-color: #eeeeee;
  border: 1px solid #ccc;
}

.cc .input-prepend .add-on,
.input-append .add-on,
.input-prepend .btn,
.input-append .btn {
  margin-left: -1px;
  -webkit-border-radius: 0;
     -moz-border-radius: 0;
          border-radius: 0;
}

.cc .input-prepend .active,
.input-append .active {
  background-color: #a9dba9;
  border-color: #46a546;
}

.cc .input-prepend .add-on,
.input-prepend .btn {
  margin-right: -1px;
}

.cc .input-prepend .add-on:first-child,
.input-prepend .btn:first-child {
  -webkit-border-radius: 3px 0 0 3px;
     -moz-border-radius: 3px 0 0 3px;
          border-radius: 3px 0 0 3px;
}

.cc .input-append input,
.input-append select,
.input-append .uneditable-input {
  -webkit-border-radius: 3px 0 0 3px;
     -moz-border-radius: 3px 0 0 3px;
          border-radius: 3px 0 0 3px;
}

.cc .input-append .uneditable-input {
  border-right-color: #ccc;
  border-left-color: #eee;
}

.cc .input-append .add-on:last-child,
.input-append .btn:last-child {
  -webkit-border-radius: 0 3px 3px 0;
     -moz-border-radius: 0 3px 3px 0;
          border-radius: 0 3px 3px 0;
}

.cc .input-prepend.input-append input,
.input-prepend.input-append select,
.input-prepend.input-append .uneditable-input {
  -webkit-border-radius: 0;
     -moz-border-radius: 0;
          border-radius: 0;
}

.cc .input-prepend.input-append .add-on:first-child,
.input-prepend.input-append .btn:first-child {
  margin-right: -1px;
  -webkit-border-radius: 3px 0 0 3px;
     -moz-border-radius: 3px 0 0 3px;
          border-radius: 3px 0 0 3px;
}

.cc .input-prepend.input-append .add-on:last-child,
.input-prepend.input-append .btn:last-child {
  margin-left: -1px;
  -webkit-border-radius: 0 3px 3px 0;
     -moz-border-radius: 0 3px 3px 0;
          border-radius: 0 3px 3px 0;
}

.cc .search-query {
  padding-right: 14px;
  padding-right: 4px \9;
  padding-left: 14px;
  padding-left: 4px \9;
  /* IE7-8 doesn't have border-radius, so don't indent the padding */

.cc   margin-bottom: 0;
  -webkit-border-radius: 14px;
     -moz-border-radius: 14px;
          border-radius: 14px;
}

.cc .form-search input,
.form-inline input,
.form-horizontal input,
.form-search textarea,
.form-inline textarea,
.form-horizontal textarea,
.form-search select,
.form-inline select,
.form-horizontal select,
.form-search .help-inline,
.form-inline .help-inline,
.form-horizontal .help-inline,
.form-search .uneditable-input,
.form-inline .uneditable-input,
.form-horizontal .uneditable-input,
.form-search .input-prepend,
.form-inline .input-prepend,
.form-horizontal .input-prepend,
.form-search .input-append,
.form-inline .input-append,
.form-horizontal .input-append {
  display: inline-block;
  *display: inline;
  margin-bottom: 0;
  *zoom: 1;
}

.cc .form-search .hide,
.form-inline .hide,
.form-horizontal .hide {
  display: none;
}

.cc .form-search label,
.form-inline label {
  display: inline-block;
}

.cc .form-search .input-append,
.form-inline .input-append,
.form-search .input-prepend,
.form-inline .input-prepend {
  margin-bottom: 0;
}

.cc .form-search .radio,
.form-search .checkbox,
.form-inline .radio,
.form-inline .checkbox {
  padding-left: 0;
  margin-bottom: 0;
  vertical-align: middle;
}

.cc .form-search .radio input[type="radio"],
.form-search .checkbox input[type="checkbox"],
.form-inline .radio input[type="radio"],
.form-inline .checkbox input[type="checkbox"] {
  float: left;
  margin-right: 3px;
  margin-left: 0;
}

.cc .control-group {
  margin-bottom: 9px;
}

.cc legend + .control-group {
  margin-top: 18px;
  -webkit-margin-top-collapse: separate;
}

.cc .form-horizontal .control-group {
  margin-bottom: 18px;
  *zoom: 1;
}

.cc .form-horizontal .control-group:before,
.form-horizontal .control-group:after {
  display: table;
  content: "";
}

.cc .form-horizontal .control-group:after {
  clear: both;
}

.cc .form-horizontal .control-label {
  float: left;
  width: 140px;
  padding-top: 5px;
  text-align: right;
}

.cc .form-horizontal .controls {
  *display: inline-block;
  *padding-left: 20px;
  margin-left: 160px;
  *margin-left: 0;
}

.cc .form-horizontal .controls:first-child {
  *padding-left: 160px;
}

.cc .form-horizontal .help-block {
  margin-top: 9px;
  margin-bottom: 0;
}

.cc .form-horizontal .form-actions {
  padding-left: 160px;
}

.cc table {
  max-width: 100%;
  background-color: transparent;
  border-collapse: collapse;
  border-spacing: 0;
}

.cc .table {
  width: 100%;
  margin-bottom: 18px;
}

.cc .table th,
.table td {
  padding: 8px;
  line-height: 18px;
  text-align: left;
  vertical-align: top;
  border-top: 1px solid #dddddd;
}

.cc .table th {
  font-weight: bold;
}

.cc .table thead th {
  vertical-align: bottom;
}

.cc .table caption + thead tr:first-child th,
.table caption + thead tr:first-child td,
.table colgroup + thead tr:first-child th,
.table colgroup + thead tr:first-child td,
.table thead:first-child tr:first-child th,
.table thead:first-child tr:first-child td {
  border-top: 0;
}

.cc .table tbody + tbody {
  border-top: 2px solid #dddddd;
}

.cc .table-condensed th,
.table-condensed td {
  padding: 4px 5px;
}

.cc .table-bordered {
  border: 1px solid #dddddd;
  border-collapse: separate;
  *border-collapse: collapsed;
  border-left: 0;
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
}

.cc .table-bordered th,
.table-bordered td {
  border-left: 1px solid #dddddd;
}

.cc .table-bordered caption + thead tr:first-child th,
.table-bordered caption + tbody tr:first-child th,
.table-bordered caption + tbody tr:first-child td,
.table-bordered colgroup + thead tr:first-child th,
.table-bordered colgroup + tbody tr:first-child th,
.table-bordered colgroup + tbody tr:first-child td,
.table-bordered thead:first-child tr:first-child th,
.table-bordered tbody:first-child tr:first-child th,
.table-bordered tbody:first-child tr:first-child td {
  border-top: 0;
}

.cc .table-bordered thead:first-child tr:first-child th:first-child,
.table-bordered tbody:first-child tr:first-child td:first-child {
  -webkit-border-top-left-radius: 4px;
          border-top-left-radius: 4px;
  -moz-border-radius-topleft: 4px;
}

.cc .table-bordered thead:first-child tr:first-child th:last-child,
.table-bordered tbody:first-child tr:first-child td:last-child {
  -webkit-border-top-right-radius: 4px;
          border-top-right-radius: 4px;
  -moz-border-radius-topright: 4px;
}

.cc .table-bordered thead:last-child tr:last-child th:first-child,
.table-bordered tbody:last-child tr:last-child td:first-child {
  -webkit-border-radius: 0 0 0 4px;
     -moz-border-radius: 0 0 0 4px;
          border-radius: 0 0 0 4px;
  -webkit-border-bottom-left-radius: 4px;
          border-bottom-left-radius: 4px;
  -moz-border-radius-bottomleft: 4px;
}

.cc .table-bordered thead:last-child tr:last-child th:last-child,
.table-bordered tbody:last-child tr:last-child td:last-child {
  -webkit-border-bottom-right-radius: 4px;
          border-bottom-right-radius: 4px;
  -moz-border-radius-bottomright: 4px;
}

.cc .table-striped tbody tr:nth-child(odd) td,
.table-striped tbody tr:nth-child(odd) th {
  background-color: #f9f9f9;
}

.cc .table tbody tr:hover td,
.table tbody tr:hover th {
  background-color: #f5f5f5;
}

.cc table .span1 {
  float: none;
  width: 44px;
  margin-left: 0;
}

.cc table .span2 {
  float: none;
  width: 124px;
  margin-left: 0;
}

.cc table .span3 {
  float: none;
  width: 204px;
  margin-left: 0;
}

.cc table .span4 {
  float: none;
  width: 284px;
  margin-left: 0;
}

.cc table .span5 {
  float: none;
  width: 364px;
  margin-left: 0;
}

.cc table .span6 {
  float: none;
  width: 444px;
  margin-left: 0;
}

.cc table .span7 {
  float: none;
  width: 524px;
  margin-left: 0;
}

.cc table .span8 {
  float: none;
  width: 604px;
  margin-left: 0;
}

.cc table .span9 {
  float: none;
  width: 684px;
  margin-left: 0;
}

.cc table .span10 {
  float: none;
  width: 764px;
  margin-left: 0;
}

.cc table .span11 {
  float: none;
  width: 844px;
  margin-left: 0;
}

.cc table .span12 {
  float: none;
  width: 924px;
  margin-left: 0;
}

.cc table .span13 {
  float: none;
  width: 1004px;
  margin-left: 0;
}

.cc table .span14 {
  float: none;
  width: 1084px;
  margin-left: 0;
}

.cc table .span15 {
  float: none;
  width: 1164px;
  margin-left: 0;
}

.cc table .span16 {
  float: none;
  width: 1244px;
  margin-left: 0;
}

.cc table .span17 {
  float: none;
  width: 1324px;
  margin-left: 0;
}

.cc table .span18 {
  float: none;
  width: 1404px;
  margin-left: 0;
}

.cc table .span19 {
  float: none;
  width: 1484px;
  margin-left: 0;
}

.cc table .span20 {
  float: none;
  width: 1564px;
  margin-left: 0;
}

.cc table .span21 {
  float: none;
  width: 1644px;
  margin-left: 0;
}

.cc table .span22 {
  float: none;
  width: 1724px;
  margin-left: 0;
}

.cc table .span23 {
  float: none;
  width: 1804px;
  margin-left: 0;
}

.cc table .span24 {
  float: none;
  width: 1884px;
  margin-left: 0;
}

.cc [class^="icon-"],
.cc [class*=" icon-"] {
  display: inline-block;
  width: 14px;
  height: 14px;
  *margin-right: .3em;
  line-height: 14px;
  vertical-align: text-top;
  background-image: url("../img/glyphicons-halflings.png");
  background-position: 14px 14px;
  background-repeat: no-repeat;
}

.cc [class^="icon-"]:last-child,
.cc [class*=" icon-"]:last-child {
  *margin-left: 0;
}

.cc .icon-white {
  background-image: url("../img/glyphicons-halflings-white.png");
}

.cc .icon-glass {
  background-position: 0      0;
}

.cc .icon-music {
  background-position: -24px 0;
}

.cc .icon-search {
  background-position: -48px 0;
}

.cc .icon-envelope {
  background-position: -72px 0;
}

.cc .icon-heart {
  background-position: -96px 0;
}

.cc .icon-star {
  background-position: -120px 0;
}

.cc .icon-star-empty {
  background-position: -144px 0;
}

.cc .icon-user {
  background-position: -168px 0;
}

.cc .icon-film {
  background-position: -192px 0;
}

.cc .icon-th-large {
  background-position: -216px 0;
}

.cc .icon-th {
  background-position: -240px 0;
}

.cc .icon-th-list {
  background-position: -264px 0;
}

.cc .icon-ok {
  background-position: -288px 0;
}

.cc .icon-remove {
  background-position: -312px 0;
}

.cc .icon-zoom-in {
  background-position: -336px 0;
}

.cc .icon-zoom-out {
  background-position: -360px 0;
}

.cc .icon-off {
  background-position: -384px 0;
}

.cc .icon-signal {
  background-position: -408px 0;
}

.cc .icon-cog {
  background-position: -432px 0;
}

.cc .icon-trash {
  background-position: -456px 0;
}

.cc .icon-home {
  background-position: 0 -24px;
}

.cc .icon-file {
  background-position: -24px -24px;
}

.cc .icon-time {
  background-position: -48px -24px;
}

.cc .icon-road {
  background-position: -72px -24px;
}

.cc .icon-download-alt {
  background-position: -96px -24px;
}

.cc .icon-download {
  background-position: -120px -24px;
}

.cc .icon-upload {
  background-position: -144px -24px;
}

.cc .icon-inbox {
  background-position: -168px -24px;
}

.cc .icon-play-circle {
  background-position: -192px -24px;
}

.cc .icon-repeat {
  background-position: -216px -24px;
}

.cc .icon-refresh {
  background-position: -240px -24px;
}

.cc .icon-list-alt {
  background-position: -264px -24px;
}

.cc .icon-lock {
  background-position: -287px -24px;
}

.cc .icon-flag {
  background-position: -312px -24px;
}

.cc .icon-headphones {
  background-position: -336px -24px;
}

.cc .icon-volume-off {
  background-position: -360px -24px;
}

.cc .icon-volume-down {
  background-position: -384px -24px;
}

.cc .icon-volume-up {
  background-position: -408px -24px;
}

.cc .icon-qrcode {
  background-position: -432px -24px;
}

.cc .icon-barcode {
  background-position: -456px -24px;
}

.cc .icon-tag {
  background-position: 0 -48px;
}

.cc .icon-tags {
  background-position: -25px -48px;
}

.cc .icon-book {
  background-position: -48px -48px;
}

.cc .icon-bookmark {
  background-position: -72px -48px;
}

.cc .icon-print {
  background-position: -96px -48px;
}

.cc .icon-camera {
  background-position: -120px -48px;
}

.cc .icon-font {
  background-position: -144px -48px;
}

.cc .icon-bold {
  background-position: -167px -48px;
}

.cc .icon-italic {
  background-position: -192px -48px;
}

.cc .icon-text-height {
  background-position: -216px -48px;
}

.cc .icon-text-width {
  background-position: -240px -48px;
}

.cc .icon-align-left {
  background-position: -264px -48px;
}

.cc .icon-align-center {
  background-position: -288px -48px;
}

.cc .icon-align-right {
  background-position: -312px -48px;
}

.cc .icon-align-justify {
  background-position: -336px -48px;
}

.cc .icon-list {
  background-position: -360px -48px;
}

.cc .icon-indent-left {
  background-position: -384px -48px;
}

.cc .icon-indent-right {
  background-position: -408px -48px;
}

.cc .icon-facetime-video {
  background-position: -432px -48px;
}

.cc .icon-picture {
  background-position: -456px -48px;
}

.cc .icon-pencil {
  background-position: 0 -72px;
}

.cc .icon-map-marker {
  background-position: -24px -72px;
}

.cc .icon-adjust {
  background-position: -48px -72px;
}

.cc .icon-tint {
  background-position: -72px -72px;
}

.cc .icon-edit {
  background-position: -96px -72px;
}

.cc .icon-share {
  background-position: -120px -72px;
}

.cc .icon-check {
  background-position: -144px -72px;
}

.cc .icon-move {
  background-position: -168px -72px;
}

.cc .icon-step-backward {
  background-position: -192px -72px;
}

.cc .icon-fast-backward {
  background-position: -216px -72px;
}

.cc .icon-backward {
  background-position: -240px -72px;
}

.cc .icon-play {
  background-position: -264px -72px;
}

.cc .icon-pause {
  background-position: -288px -72px;
}

.cc .icon-stop {
  background-position: -312px -72px;
}

.cc .icon-forward {
  background-position: -336px -72px;
}

.cc .icon-fast-forward {
  background-position: -360px -72px;
}

.cc .icon-step-forward {
  background-position: -384px -72px;
}

.cc .icon-eject {
  background-position: -408px -72px;
}

.cc .icon-chevron-left {
  background-position: -432px -72px;
}

.cc .icon-chevron-right {
  background-position: -456px -72px;
}

.cc .icon-plus-sign {
  background-position: 0 -96px;
}

.cc .icon-minus-sign {
  background-position: -24px -96px;
}

.cc .icon-remove-sign {
  background-position: -48px -96px;
}

.cc .icon-ok-sign {
  background-position: -72px -96px;
}

.cc .icon-question-sign {
  background-position: -96px -96px;
}

.cc .icon-info-sign {
  background-position: -120px -96px;
}

.cc .icon-screenshot {
  background-position: -144px -96px;
}

.cc .icon-remove-circle {
  background-position: -168px -96px;
}

.cc .icon-ok-circle {
  background-position: -192px -96px;
}

.cc .icon-ban-circle {
  background-position: -216px -96px;
}

.cc .icon-arrow-left {
  background-position: -240px -96px;
}

.cc .icon-arrow-right {
  background-position: -264px -96px;
}

.cc .icon-arrow-up {
  background-position: -289px -96px;
}

.cc .icon-arrow-down {
  background-position: -312px -96px;
}

.cc .icon-share-alt {
  background-position: -336px -96px;
}

.cc .icon-resize-full {
  background-position: -360px -96px;
}

.cc .icon-resize-small {
  background-position: -384px -96px;
}

.cc .icon-plus {
  background-position: -408px -96px;
}

.cc .icon-minus {
  background-position: -433px -96px;
}

.cc .icon-asterisk {
  background-position: -456px -96px;
}

.cc .icon-exclamation-sign {
  background-position: 0 -120px;
}

.cc .icon-gift {
  background-position: -24px -120px;
}

.cc .icon-leaf {
  background-position: -48px -120px;
}

.cc .icon-fire {
  background-position: -72px -120px;
}

.cc .icon-eye-open {
  background-position: -96px -120px;
}

.cc .icon-eye-close {
  background-position: -120px -120px;
}

.cc .icon-warning-sign {
  background-position: -144px -120px;
}

.cc .icon-plane {
  background-position: -168px -120px;
}

.cc .icon-calendar {
  background-position: -192px -120px;
}

.cc .icon-random {
  background-position: -216px -120px;
}

.cc .icon-comment {
  background-position: -240px -120px;
}

.cc .icon-magnet {
  background-position: -264px -120px;
}

.cc .icon-chevron-up {
  background-position: -288px -120px;
}

.cc .icon-chevron-down {
  background-position: -313px -119px;
}

.cc .icon-retweet {
  background-position: -336px -120px;
}

.cc .icon-shopping-cart {
  background-position: -360px -120px;
}

.cc .icon-folder-close {
  background-position: -384px -120px;
}

.cc .icon-folder-open {
  background-position: -408px -120px;
}

.cc .icon-resize-vertical {
  background-position: -432px -119px;
}

.cc .icon-resize-horizontal {
  background-position: -456px -118px;
}

.cc .icon-hdd {
  background-position: 0 -144px;
}

.cc .icon-bullhorn {
  background-position: -24px -144px;
}

.cc .icon-bell {
  background-position: -48px -144px;
}

.cc .icon-certificate {
  background-position: -72px -144px;
}

.cc .icon-thumbs-up {
  background-position: -96px -144px;
}

.cc .icon-thumbs-down {
  background-position: -120px -144px;
}

.cc .icon-hand-right {
  background-position: -144px -144px;
}

.cc .icon-hand-left {
  background-position: -168px -144px;
}

.cc .icon-hand-up {
  background-position: -192px -144px;
}

.cc .icon-hand-down {
  background-position: -216px -144px;
}

.cc .icon-circle-arrow-right {
  background-position: -240px -144px;
}

.cc .icon-circle-arrow-left {
  background-position: -264px -144px;
}

.cc .icon-circle-arrow-up {
  background-position: -288px -144px;
}

.cc .icon-circle-arrow-down {
  background-position: -312px -144px;
}

.cc .icon-globe {
  background-position: -336px -144px;
}

.cc .icon-wrench {
  background-position: -360px -144px;
}

.cc .icon-tasks {
  background-position: -384px -144px;
}

.cc .icon-filter {
  background-position: -408px -144px;
}

.cc .icon-briefcase {
  background-position: -432px -144px;
}

.cc .icon-fullscreen {
  background-position: -456px -144px;
}

.cc .dropup,
.cc .dropdown {
  position: relative;
}

.cc .dropdown-toggle {
  *margin-bottom: -3px;
}

.cc .dropdown-toggle:active,
.cc .open .dropdown-toggle {
  outline: 0;
}

.cc .caret {
  display: inline-block;
  width: 0;
  height: 0;
  vertical-align: top;
  border-top: 4px solid #000000;
  border-right: 4px solid transparent;
  border-left: 4px solid transparent;
  content: "";
  opacity: 0.3;
  filter: alpha(opacity=30);
}

.cc .dropdown .caret {
  margin-top: 8px;
  margin-left: 2px;
}

.cc .dropdown:hover .caret,
.open .caret {
  opacity: 1;
  filter: alpha(opacity=100);
}

.cc .dropdown-menu {
  position: absolute;
  top: 100%;
  left: 0;
  z-index: 1000;
  display: none;
  float: left;
  min-width: 160px;
  padding: 4px 0;
  margin: 1px 0 0;
  list-style: none;
  background-color: #ffffff;
  border: 1px solid #ccc;
  border: 1px solid rgba(0, 0, 0, 0.2);
  *border-right-width: 2px;
  *border-bottom-width: 2px;
  -webkit-border-radius: 5px;
     -moz-border-radius: 5px;
          border-radius: 5px;
  -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
     -moz-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
          box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
  -webkit-background-clip: padding-box;
     -moz-background-clip: padding;
          background-clip: padding-box;
}

.cc .dropdown-menu.pull-right {
  right: 0;
  left: auto;
}

.cc .dropdown-menu .divider {
  *width: 100%;
  height: 1px;
  margin: 8px 1px;
  *margin: -5px 0 5px;
  overflow: hidden;
  background-color: #e5e5e5;
  border-bottom: 1px solid #ffffff;
}

.cc .dropdown-menu a {
  display: block;
  padding: 3px 15px;
  clear: both;
  font-weight: normal;
  line-height: 18px;
  color: #333333;
  white-space: nowrap;
}

.cc .dropdown-menu li > a:hover,
.dropdown-menu .active > a,
.dropdown-menu .active > a:hover {
  color: #ffffff;
  text-decoration: none;
  background-color: #0088cc;
}

.cc .open {
  *z-index: 1000;
}

.cc .open > .dropdown-menu {
  display: block;
}

.cc .pull-right > .dropdown-menu {
  right: 0;
  left: auto;
}

.cc .dropup .caret,
.navbar-fixed-bottom .dropdown .caret {
  border-top: 0;
  border-bottom: 4px solid #000000;
  content: "\2191";
}

.cc .dropup .dropdown-menu,
.navbar-fixed-bottom .dropdown .dropdown-menu {
  top: auto;
  bottom: 100%;
  margin-bottom: 1px;
}

.cc .typeahead {
  margin-top: 2px;
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
}

.cc .well {
  min-height: 20px;
  padding: 19px;
  margin-bottom: 20px;
  background-color: #f5f5f5;
  border: 1px solid #eee;
  border: 1px solid rgba(0, 0, 0, 0.05);
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
  -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
     -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
          box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.05);
}

.cc .well blockquote {
  border-color: #ddd;
  border-color: rgba(0, 0, 0, 0.15);
}

.cc .well-large {
  padding: 24px;
  -webkit-border-radius: 6px;
     -moz-border-radius: 6px;
          border-radius: 6px;
}

.cc .well-small {
  padding: 9px;
  -webkit-border-radius: 3px;
     -moz-border-radius: 3px;
          border-radius: 3px;
}

.cc .fade {
  opacity: 0;
  -webkit-transition: opacity 0.15s linear;
     -moz-transition: opacity 0.15s linear;
      -ms-transition: opacity 0.15s linear;
       -o-transition: opacity 0.15s linear;
          transition: opacity 0.15s linear;
}

.cc .fade.in {
  opacity: 1;
}

.cc .collapse {
  position: relative;
  height: 0;
  overflow: hidden;
  -webkit-transition: height 0.35s ease;
     -moz-transition: height 0.35s ease;
      -ms-transition: height 0.35s ease;
       -o-transition: height 0.35s ease;
          transition: height 0.35s ease;
}

.cc .collapse.in {
  height: auto;
}

.cc .close {
  float: right;
  font-size: 20px;
  font-weight: bold;
  line-height: 18px;
  color: #000000;
  text-shadow: 0 1px 0 #ffffff;
  opacity: 0.2;
  filter: alpha(opacity=20);
}

.cc .close:hover {
  color: #000000;
  text-decoration: none;
  cursor: pointer;
  opacity: 0.4;
  filter: alpha(opacity=40);
}

.cc button.close {
  padding: 0;
  cursor: pointer;
  background: transparent;
  border: 0;
  -webkit-appearance: none;
}

.cc .btn {
  display: inline-block;
  *display: inline;
  padding: 4px 10px 4px;
  margin-bottom: 0;
  *margin-left: .3em;
  font-size: 13px;
  line-height: 18px;
  *line-height: 20px;
  color: #333333;
  text-align: center;
  text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75);
  vertical-align: middle;
  cursor: pointer;
  background-color: #f5f5f5;
  *background-color: #e6e6e6;
  background-image: -ms-linear-gradient(top, #ffffff, #e6e6e6);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ffffff), to(#e6e6e6));
  background-image: -webkit-linear-gradient(top, #ffffff, #e6e6e6);
  background-image: -o-linear-gradient(top, #ffffff, #e6e6e6);
  background-image: linear-gradient(top, #ffffff, #e6e6e6);
  background-image: -moz-linear-gradient(top, #ffffff, #e6e6e6);
  background-repeat: repeat-x;
  border: 1px solid #cccccc;
  *border: 0;
  border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
  border-color: #e6e6e6 #e6e6e6 #bfbfbf;
  border-bottom-color: #b3b3b3;
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#ffffff', endColorstr='#e6e6e6', GradientType=0);
  filter: progid:dximagetransform.microsoft.gradient(enabled=false);
  *zoom: 1;
  -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
     -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
          box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
}

.cc .btn:hover,
.cc .btn:active,
.cc .btn.active,
.cc .btn.disabled,
.cc .btn[disabled] {
  background-color: #e6e6e6;
  *background-color: #d9d9d9;
}

.cc .btn:active,
.cc .btn.active {
  background-color: #cccccc \9;
}

.cc .btn:first-child {
  *margin-left: 0;
}

.cc .btn:hover {
  color: #333333;
  text-decoration: none;
  background-color: #e6e6e6;
  *background-color: #d9d9d9;
  /* Buttons in IE7 don't get borders, so darken on hover */

.cc   background-position: 0 -15px;
  -webkit-transition: background-position 0.1s linear;
     -moz-transition: background-position 0.1s linear;
      -ms-transition: background-position 0.1s linear;
       -o-transition: background-position 0.1s linear;
          transition: background-position 0.1s linear;
}

.cc .btn:focus {
  outline: thin dotted #333;
  outline: 5px auto -webkit-focus-ring-color;
  outline-offset: -2px;
}

.cc .btn.active,
.cc .btn:active {
  background-color: #e6e6e6;
  background-color: #d9d9d9 \9;
  background-image: none;
  outline: 0;
  -webkit-box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
     -moz-box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
          box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
}

.cc .btn.disabled,
.cc .btn[disabled] {
  cursor: default;
  background-color: #e6e6e6;
  background-image: none;
  opacity: 0.65;
  filter: alpha(opacity=65);
  -webkit-box-shadow: none;
     -moz-box-shadow: none;
          box-shadow: none;
}

.cc .btn-large {
  padding: 9px 14px;
  font-size: 15px;
  line-height: normal;
  -webkit-border-radius: 5px;
     -moz-border-radius: 5px;
          border-radius: 5px;
}

.cc .btn-large [class^="icon-"] {
  margin-top: 1px;
}

.cc .btn-small {
  padding: 5px 9px;
  font-size: 11px;
  line-height: 16px;
}

.cc .btn-small [class^="icon-"] {
  margin-top: -1px;
}

.cc .btn-mini {
  padding: 2px 6px;
  font-size: 11px;
  line-height: 14px;
}

.cc .btn-primary,
.cc .btn-primary:hover,
.cc .btn-warning,
.cc .btn-warning:hover,
.cc .btn-danger,
.cc .btn-danger:hover,
.cc .btn-success,
.cc .btn-success:hover,
.cc .btn-info,
.cc .btn-info:hover,
.cc .btn-inverse,
.cc .btn-inverse:hover {
  color: #ffffff;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
}

.cc .btn-primary.active,
.cc .btn-warning.active,
.cc .btn-danger.active,
.cc .btn-success.active,
.cc .btn-info.active,
.cc .btn-inverse.active {
  color: rgba(255, 255, 255, 0.75);
}

.cc .btn {
  border-color: #ccc;
  border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
}

.cc .btn-primary {
  background-color: #0074cc;
  *background-color: #0055cc;
  background-image: -ms-linear-gradient(top, #0088cc, #0055cc);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#0088cc), to(#0055cc));
  background-image: -webkit-linear-gradient(top, #0088cc, #0055cc);
  background-image: -o-linear-gradient(top, #0088cc, #0055cc);
  background-image: -moz-linear-gradient(top, #0088cc, #0055cc);
  background-image: linear-gradient(top, #0088cc, #0055cc);
  background-repeat: repeat-x;
  border-color: #0055cc #0055cc #003580;
  border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#0088cc', endColorstr='#0055cc', GradientType=0);
  filter: progid:dximagetransform.microsoft.gradient(enabled=false);
}

.cc .btn-primary:hover,
.cc .btn-primary:active,
.cc .btn-primary.active,
.cc .btn-primary.disabled,
.cc .btn-primary[disabled] {
  background-color: #0055cc;
  *background-color: #004ab3;
}

.cc .btn-primary:active,
.cc .btn-primary.active {
  background-color: #004099 \9;
}

.cc .btn-warning {
  background-color: #faa732;
  *background-color: #f89406;
  background-image: -ms-linear-gradient(top, #fbb450, #f89406);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#fbb450), to(#f89406));
  background-image: -webkit-linear-gradient(top, #fbb450, #f89406);
  background-image: -o-linear-gradient(top, #fbb450, #f89406);
  background-image: -moz-linear-gradient(top, #fbb450, #f89406);
  background-image: linear-gradient(top, #fbb450, #f89406);
  background-repeat: repeat-x;
  border-color: #f89406 #f89406 #ad6704;
  border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#fbb450', endColorstr='#f89406', GradientType=0);
  filter: progid:dximagetransform.microsoft.gradient(enabled=false);
}

.cc .btn-warning:hover,
.cc .btn-warning:active,
.cc .btn-warning.active,
.cc .btn-warning.disabled,
.cc .btn-warning[disabled] {
  background-color: #f89406;
  *background-color: #df8505;
}

.cc .btn-warning:active,
.cc .btn-warning.active {
  background-color: #c67605 \9;
}

.cc .btn-danger {
  background-color: #da4f49;
  *background-color: #bd362f;
  background-image: -ms-linear-gradient(top, #ee5f5b, #bd362f);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ee5f5b), to(#bd362f));
  background-image: -webkit-linear-gradient(top, #ee5f5b, #bd362f);
  background-image: -o-linear-gradient(top, #ee5f5b, #bd362f);
  background-image: -moz-linear-gradient(top, #ee5f5b, #bd362f);
  background-image: linear-gradient(top, #ee5f5b, #bd362f);
  background-repeat: repeat-x;
  border-color: #bd362f #bd362f #802420;
  border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#ee5f5b', endColorstr='#bd362f', GradientType=0);
  filter: progid:dximagetransform.microsoft.gradient(enabled=false);
}

.cc .btn-danger:hover,
.cc .btn-danger:active,
.cc .btn-danger.active,
.cc .btn-danger.disabled,
.cc .btn-danger[disabled] {
  background-color: #bd362f;
  *background-color: #a9302a;
}

.cc .btn-danger:active,
.cc .btn-danger.active {
  background-color: #942a25 \9;
}

.cc .btn-success {
  background-color: #5bb75b;
  *background-color: #51a351;
  background-image: -ms-linear-gradient(top, #62c462, #51a351);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#62c462), to(#51a351));
  background-image: -webkit-linear-gradient(top, #62c462, #51a351);
  background-image: -o-linear-gradient(top, #62c462, #51a351);
  background-image: -moz-linear-gradient(top, #62c462, #51a351);
  background-image: linear-gradient(top, #62c462, #51a351);
  background-repeat: repeat-x;
  border-color: #51a351 #51a351 #387038;
  border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#62c462', endColorstr='#51a351', GradientType=0);
  filter: progid:dximagetransform.microsoft.gradient(enabled=false);
}

.cc .btn-success:hover,
.cc .btn-success:active,
.cc .btn-success.active,
.cc .btn-success.disabled,
.cc .btn-success[disabled] {
  background-color: #51a351;
  *background-color: #499249;
}

.cc .btn-success:active,
.cc .btn-success.active {
  background-color: #408140 \9;
}

.cc .btn-info {
  background-color: #49afcd;
  *background-color: #2f96b4;
  background-image: -ms-linear-gradient(top, #5bc0de, #2f96b4);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#5bc0de), to(#2f96b4));
  background-image: -webkit-linear-gradient(top, #5bc0de, #2f96b4);
  background-image: -o-linear-gradient(top, #5bc0de, #2f96b4);
  background-image: -moz-linear-gradient(top, #5bc0de, #2f96b4);
  background-image: linear-gradient(top, #5bc0de, #2f96b4);
  background-repeat: repeat-x;
  border-color: #2f96b4 #2f96b4 #1f6377;
  border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#5bc0de', endColorstr='#2f96b4', GradientType=0);
  filter: progid:dximagetransform.microsoft.gradient(enabled=false);
}

.cc .btn-info:hover,
.cc .btn-info:active,
.cc .btn-info.active,
.cc .btn-info.disabled,
.cc .btn-info[disabled] {
  background-color: #2f96b4;
  *background-color: #2a85a0;
}

.cc .btn-info:active,
.cc .btn-info.active {
  background-color: #24748c \9;
}

.cc .btn-inverse {
  background-color: #414141;
  *background-color: #222222;
  background-image: -ms-linear-gradient(top, #555555, #222222);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#555555), to(#222222));
  background-image: -webkit-linear-gradient(top, #555555, #222222);
  background-image: -o-linear-gradient(top, #555555, #222222);
  background-image: -moz-linear-gradient(top, #555555, #222222);
  background-image: linear-gradient(top, #555555, #222222);
  background-repeat: repeat-x;
  border-color: #222222 #222222 #000000;
  border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#555555', endColorstr='#222222', GradientType=0);
  filter: progid:dximagetransform.microsoft.gradient(enabled=false);
}

.cc .btn-inverse:hover,
.cc .btn-inverse:active,
.cc .btn-inverse.active,
.cc .btn-inverse.disabled,
.cc .btn-inverse[disabled] {
  background-color: #222222;
  *background-color: #151515;
}

.cc .btn-inverse:active,
.cc .btn-inverse.active {
  background-color: #080808 \9;
}

.cc button.btn,
.cc input[type="submit"].btn {
  *padding-top: 2px;
  *padding-bottom: 2px;
}

.cc button.btn::-moz-focus-inner,
.cc input[type="submit"].btn::-moz-focus-inner {
  padding: 0;
  border: 0;
}

.cc button.btn.btn-large,
.cc input[type="submit"].btn.btn-large {
  *padding-top: 7px;
  *padding-bottom: 7px;
}

.cc button.btn.btn-small,
.cc input[type="submit"].btn.btn-small {
  *padding-top: 3px;
  *padding-bottom: 3px;
}

.cc button.btn.btn-mini,
.cc input[type="submit"].btn.btn-mini {
  *padding-top: 1px;
  *padding-bottom: 1px;
}

.cc .btn-group {
  position: relative;
  *margin-left: .3em;
  *zoom: 1;
}

.cc .btn-group:before,
.cc .btn-group:after {
  display: table;
  content: "";
}

.cc .btn-group:after {
  clear: both;
}

.cc .btn-group:first-child {
  *margin-left: 0;
}

.cc .btn-group + .btn-group {
  margin-left: 5px;
}

.cc .btn-toolbar {
  margin-top: 9px;
  margin-bottom: 9px;
}

.cc .btn-toolbar .btn-group {
  display: inline-block;
  *display: inline;
  /* IE7 inline-block hack */

.cc   *zoom: 1;
}

.cc .btn-group > .btn {
  position: relative;
  float: left;
  margin-left: -1px;
  -webkit-border-radius: 0;
     -moz-border-radius: 0;
          border-radius: 0;
}

.cc .btn-group > .btn:first-child {
  margin-left: 0;
  -webkit-border-bottom-left-radius: 4px;
          border-bottom-left-radius: 4px;
  -webkit-border-top-left-radius: 4px;
          border-top-left-radius: 4px;
  -moz-border-radius-bottomleft: 4px;
  -moz-border-radius-topleft: 4px;
}

.cc .btn-group > .btn:last-child,
.btn-group > .dropdown-toggle {
  -webkit-border-top-right-radius: 4px;
          border-top-right-radius: 4px;
  -webkit-border-bottom-right-radius: 4px;
          border-bottom-right-radius: 4px;
  -moz-border-radius-topright: 4px;
  -moz-border-radius-bottomright: 4px;
}

.cc .btn-group > .btn.large:first-child {
  margin-left: 0;
  -webkit-border-bottom-left-radius: 6px;
          border-bottom-left-radius: 6px;
  -webkit-border-top-left-radius: 6px;
          border-top-left-radius: 6px;
  -moz-border-radius-bottomleft: 6px;
  -moz-border-radius-topleft: 6px;
}

.cc .btn-group > .btn.large:last-child,
.btn-group > .large.dropdown-toggle {
  -webkit-border-top-right-radius: 6px;
          border-top-right-radius: 6px;
  -webkit-border-bottom-right-radius: 6px;
          border-bottom-right-radius: 6px;
  -moz-border-radius-topright: 6px;
  -moz-border-radius-bottomright: 6px;
}

.cc .btn-group > .btn:hover,
.btn-group > .btn:focus,
.btn-group > .btn:active,
.btn-group > .btn.active {
  z-index: 2;
}

.cc .btn-group .dropdown-toggle:active,
.btn-group.open .dropdown-toggle {
  outline: 0;
}

.cc .btn-group > .dropdown-toggle {
  *padding-top: 4px;
  padding-right: 8px;
  *padding-bottom: 4px;
  padding-left: 8px;
  -webkit-box-shadow: inset 1px 0 0 rgba(255, 255, 255, 0.125), inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
     -moz-box-shadow: inset 1px 0 0 rgba(255, 255, 255, 0.125), inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
          box-shadow: inset 1px 0 0 rgba(255, 255, 255, 0.125), inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
}

.cc .btn-group > .btn-mini.dropdown-toggle {
  padding-right: 5px;
  padding-left: 5px;
}

.cc .btn-group > .btn-small.dropdown-toggle {
  *padding-top: 4px;
  *padding-bottom: 4px;
}

.cc .btn-group > .btn-large.dropdown-toggle {
  padding-right: 12px;
  padding-left: 12px;
}

.cc .btn-group.open .dropdown-toggle {
  background-image: none;
  -webkit-box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
     -moz-box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
          box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
}

.cc .btn-group.open .btn.dropdown-toggle {
  background-color: #e6e6e6;
}

.cc .btn-group.open .btn-primary.dropdown-toggle {
  background-color: #0055cc;
}

.cc .btn-group.open .btn-warning.dropdown-toggle {
  background-color: #f89406;
}

.cc .btn-group.open .btn-danger.dropdown-toggle {
  background-color: #bd362f;
}

.cc .btn-group.open .btn-success.dropdown-toggle {
  background-color: #51a351;
}

.cc .btn-group.open .btn-info.dropdown-toggle {
  background-color: #2f96b4;
}

.cc .btn-group.open .btn-inverse.dropdown-toggle {
  background-color: #222222;
}

.cc .btn .caret {
  margin-top: 7px;
  margin-left: 0;
}

.cc .btn:hover .caret,
.open.btn-group .caret {
  opacity: 1;
  filter: alpha(opacity=100);
}

.cc .btn-mini .caret {
  margin-top: 5px;
}

.cc .btn-small .caret {
  margin-top: 6px;
}

.cc .btn-large .caret {
  margin-top: 6px;
  border-top-width: 5px;
  border-right-width: 5px;
  border-left-width: 5px;
}

.cc .dropup .btn-large .caret {
  border-top: 0;
  border-bottom: 5px solid #000000;
}

.cc .btn-primary .caret,
.btn-warning .caret,
.btn-danger .caret,
.btn-info .caret,
.btn-success .caret,
.btn-inverse .caret {
  border-top-color: #ffffff;
  border-bottom-color: #ffffff;
  opacity: 0.75;
  filter: alpha(opacity=75);
}

.cc .alert {
  padding: 8px 35px 8px 14px;
  margin-bottom: 18px;
  color: #c09853;
  text-shadow: 0 1px 0 rgba(255, 255, 255, 0.5);
  background-color: #fcf8e3;
  border: 1px solid #fbeed5;
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
}

.cc .alert-heading {
  color: inherit;
}

.cc .alert .close {
  position: relative;
  top: -2px;
  right: -21px;
  line-height: 18px;
}

.cc .alert-success {
  color: #468847;
  background-color: #dff0d8;
  border-color: #d6e9c6;
}

.cc .alert-danger,
.cc .alert-error {
  color: #b94a48;
  background-color: #f2dede;
  border-color: #eed3d7;
}

.cc .alert-info {
  color: #3a87ad;
  background-color: #d9edf7;
  border-color: #bce8f1;
}

.cc .alert-block {
  padding-top: 14px;
  padding-bottom: 14px;
}

.cc .alert-block > p,
.alert-block > ul {
  margin-bottom: 0;
}

.cc .alert-block p + p {
  margin-top: 5px;
}

.cc .nav {
  margin-bottom: 18px;
  margin-left: 0;
  list-style: none;
}

.cc .nav > li > a {
  display: block;
}

.cc .nav > li > a:hover {
  text-decoration: none;
  background-color: #eeeeee;
}

.cc .nav > .pull-right {
  float: right;
}

.cc .nav .nav-header {
  display: block;
  padding: 3px 15px;
  font-size: 11px;
  font-weight: bold;
  line-height: 18px;
  color: #999999;
  text-shadow: 0 1px 0 rgba(255, 255, 255, 0.5);
  text-transform: uppercase;
}

.cc .nav li + .nav-header {
  margin-top: 9px;
}

.cc .nav-list {
  padding-right: 15px;
  padding-left: 15px;
  margin-bottom: 0;
}

.cc .nav-list > li > a,
.nav-list .nav-header {
  margin-right: -15px;
  margin-left: -15px;
  text-shadow: 0 1px 0 rgba(255, 255, 255, 0.5);
}

.cc .nav-list > li > a {
  padding: 3px 15px;
}

.cc .nav-list > .active > a,
.nav-list > .active > a:hover {
  color: #ffffff;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.2);
  background-color: #0088cc;
}

.cc .nav-list [class^="icon-"] {
  margin-right: 2px;
}

.cc .nav-list .divider {
  *width: 100%;
  height: 1px;
  margin: 8px 1px;
  *margin: -5px 0 5px;
  overflow: hidden;
  background-color: #e5e5e5;
  border-bottom: 1px solid #ffffff;
}

.cc .nav-tabs,
.cc .nav-pills {
  *zoom: 1;
}

.cc .nav-tabs:before,
.cc .nav-pills:before,
.cc .nav-tabs:after,
.cc .nav-pills:after {
  display: table;
  content: "";
}

.cc .nav-tabs:after,
.cc .nav-pills:after {
  clear: both;
}

.cc .nav-tabs > li,
.nav-pills > li {
  float: left;
}

.cc .nav-tabs > li > a,
.nav-pills > li > a {
  padding-right: 12px;
  padding-left: 12px;
  margin-right: 2px;
  line-height: 14px;
}

.cc .nav-tabs {
  border-bottom: 1px solid #ddd;
}

.cc .nav-tabs > li {
  margin-bottom: -1px;
}

.cc .nav-tabs > li > a {
  padding-top: 8px;
  padding-bottom: 8px;
  line-height: 18px;
  border: 1px solid transparent;
  -webkit-border-radius: 4px 4px 0 0;
     -moz-border-radius: 4px 4px 0 0;
          border-radius: 4px 4px 0 0;
}

.cc .nav-tabs > li > a:hover {
  border-color: #eeeeee #eeeeee #dddddd;
}

.cc .nav-tabs > .active > a,
.nav-tabs > .active > a:hover {
  color: #555555;
  cursor: default;
  background-color: #ffffff;
  border: 1px solid #ddd;
  border-bottom-color: transparent;
}

.cc .nav-pills > li > a {
  padding-top: 8px;
  padding-bottom: 8px;
  margin-top: 2px;
  margin-bottom: 2px;
  -webkit-border-radius: 5px;
     -moz-border-radius: 5px;
          border-radius: 5px;
}

.cc .nav-pills > .active > a,
.nav-pills > .active > a:hover {
  color: #ffffff;
  background-color: #0088cc;
}

.cc .nav-stacked > li {
  float: none;
}

.cc .nav-stacked > li > a {
  margin-right: 0;
}

.cc .nav-tabs.nav-stacked {
  border-bottom: 0;
}

.cc .nav-tabs.nav-stacked > li > a {
  border: 1px solid #ddd;
  -webkit-border-radius: 0;
     -moz-border-radius: 0;
          border-radius: 0;
}

.cc .nav-tabs.nav-stacked > li:first-child > a {
  -webkit-border-radius: 4px 4px 0 0;
     -moz-border-radius: 4px 4px 0 0;
          border-radius: 4px 4px 0 0;
}

.cc .nav-tabs.nav-stacked > li:last-child > a {
  -webkit-border-radius: 0 0 4px 4px;
     -moz-border-radius: 0 0 4px 4px;
          border-radius: 0 0 4px 4px;
}

.cc .nav-tabs.nav-stacked > li > a:hover {
  z-index: 2;
  border-color: #ddd;
}

.cc .nav-pills.nav-stacked > li > a {
  margin-bottom: 3px;
}

.cc .nav-pills.nav-stacked > li:last-child > a {
  margin-bottom: 1px;
}

.cc .nav-tabs .dropdown-menu {
  -webkit-border-radius: 0 0 5px 5px;
     -moz-border-radius: 0 0 5px 5px;
          border-radius: 0 0 5px 5px;
}

.cc .nav-pills .dropdown-menu {
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
}

.cc .nav-tabs .dropdown-toggle .caret,
.nav-pills .dropdown-toggle .caret {
  margin-top: 6px;
  border-top-color: #0088cc;
  border-bottom-color: #0088cc;
}

.cc .nav-tabs .dropdown-toggle:hover .caret,
.nav-pills .dropdown-toggle:hover .caret {
  border-top-color: #005580;
  border-bottom-color: #005580;
}

.cc .nav-tabs .active .dropdown-toggle .caret,
.nav-pills .active .dropdown-toggle .caret {
  border-top-color: #333333;
  border-bottom-color: #333333;
}

.cc .nav > .dropdown.active > a:hover {
  color: #000000;
  cursor: pointer;
}

.cc .nav-tabs .open .dropdown-toggle,
.nav-pills .open .dropdown-toggle,
.nav > li.dropdown.open.active > a:hover {
  color: #ffffff;
  background-color: #999999;
  border-color: #999999;
}

.cc .nav li.dropdown.open .caret,
.nav li.dropdown.open.active .caret,
.nav li.dropdown.open a:hover .caret {
  border-top-color: #ffffff;
  border-bottom-color: #ffffff;
  opacity: 1;
  filter: alpha(opacity=100);
}

.cc .tabs-stacked .open > a:hover {
  border-color: #999999;
}

.cc .tabbable {
  *zoom: 1;
}

.cc .tabbable:before,
.cc .tabbable:after {
  display: table;
  content: "";
}

.cc .tabbable:after {
  clear: both;
}

.cc .tab-content {
  overflow: auto;
}

.cc .tabs-below > .nav-tabs,
.tabs-right > .nav-tabs,
.tabs-left > .nav-tabs {
  border-bottom: 0;
}

.cc .tab-content > .tab-pane,
.pill-content > .pill-pane {
  display: none;
}

.cc .tab-content > .active,
.pill-content > .active {
  display: block;
}

.cc .tabs-below > .nav-tabs {
  border-top: 1px solid #ddd;
}

.cc .tabs-below > .nav-tabs > li {
  margin-top: -1px;
  margin-bottom: 0;
}

.cc .tabs-below > .nav-tabs > li > a {
  -webkit-border-radius: 0 0 4px 4px;
     -moz-border-radius: 0 0 4px 4px;
          border-radius: 0 0 4px 4px;
}

.cc .tabs-below > .nav-tabs > li > a:hover {
  border-top-color: #ddd;
  border-bottom-color: transparent;
}

.cc .tabs-below > .nav-tabs > .active > a,
.tabs-below > .nav-tabs > .active > a:hover {
  border-color: transparent #ddd #ddd #ddd;
}

.cc .tabs-left > .nav-tabs > li,
.tabs-right > .nav-tabs > li {
  float: none;
}

.cc .tabs-left > .nav-tabs > li > a,
.tabs-right > .nav-tabs > li > a {
  min-width: 74px;
  margin-right: 0;
  margin-bottom: 3px;
}

.cc .tabs-left > .nav-tabs {
  float: left;
  margin-right: 19px;
  border-right: 1px solid #ddd;
}

.cc .tabs-left > .nav-tabs > li > a {
  margin-right: -1px;
  -webkit-border-radius: 4px 0 0 4px;
     -moz-border-radius: 4px 0 0 4px;
          border-radius: 4px 0 0 4px;
}

.cc .tabs-left > .nav-tabs > li > a:hover {
  border-color: #eeeeee #dddddd #eeeeee #eeeeee;
}

.cc .tabs-left > .nav-tabs .active > a,
.tabs-left > .nav-tabs .active > a:hover {
  border-color: #ddd transparent #ddd #ddd;
  *border-right-color: #ffffff;
}

.cc .tabs-right > .nav-tabs {
  float: right;
  margin-left: 19px;
  border-left: 1px solid #ddd;
}

.cc .tabs-right > .nav-tabs > li > a {
  margin-left: -1px;
  -webkit-border-radius: 0 4px 4px 0;
     -moz-border-radius: 0 4px 4px 0;
          border-radius: 0 4px 4px 0;
}

.cc .tabs-right > .nav-tabs > li > a:hover {
  border-color: #eeeeee #eeeeee #eeeeee #dddddd;
}

.cc .tabs-right > .nav-tabs .active > a,
.tabs-right > .nav-tabs .active > a:hover {
  border-color: #ddd #ddd #ddd transparent;
  *border-left-color: #ffffff;
}

.cc .navbar {
  *position: relative;
  *z-index: 2;
  margin-bottom: 18px;
  overflow: visible;
}

.cc .navbar-inner {
  min-height: 40px;
  padding-right: 20px;
  padding-left: 20px;
  background-color: #2c2c2c;
  background-image: -moz-linear-gradient(top, #333333, #222222);
  background-image: -ms-linear-gradient(top, #333333, #222222);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#333333), to(#222222));
  background-image: -webkit-linear-gradient(top, #333333, #222222);
  background-image: -o-linear-gradient(top, #333333, #222222);
  background-image: linear-gradient(top, #333333, #222222);
  background-repeat: repeat-x;
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#333333', endColorstr='#222222', GradientType=0);
  -webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25), inset 0 -1px 0 rgba(0, 0, 0, 0.1);
     -moz-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25), inset 0 -1px 0 rgba(0, 0, 0, 0.1);
          box-shadow: 0 1px 3px rgba(0, 0, 0, 0.25), inset 0 -1px 0 rgba(0, 0, 0, 0.1);
}

.cc .navbar .container {
  width: auto;
}

.cc .nav-collapse.collapse {
  height: auto;
}

.cc .navbar {
  color: #999999;
}

.cc .navbar .brand:hover {
  text-decoration: none;
}

.cc .navbar .brand {
  display: block;
  float: left;
  padding: 8px 20px 12px;
  margin-left: -20px;
  font-size: 20px;
  font-weight: 200;
  line-height: 1;
  color: #999999;
}

.cc .navbar .navbar-text {
  margin-bottom: 0;
  line-height: 40px;
}

.cc .navbar .navbar-link {
  color: #999999;
}

.cc .navbar .navbar-link:hover {
  color: #ffffff;
}

.cc .navbar .btn,
.navbar .btn-group {
  margin-top: 5px;
}

.cc .navbar .btn-group .btn {
  margin: 0;
}

.cc .navbar-form {
  margin-bottom: 0;
  *zoom: 1;
}

.cc .navbar-form:before,
.cc .navbar-form:after {
  display: table;
  content: "";
}

.cc .navbar-form:after {
  clear: both;
}

.cc .navbar-form input,
.navbar-form select,
.navbar-form .radio,
.navbar-form .checkbox {
  margin-top: 5px;
}

.cc .navbar-form input,
.navbar-form select {
  display: inline-block;
  margin-bottom: 0;
}

.cc .navbar-form input[type="image"],
.navbar-form input[type="checkbox"],
.navbar-form input[type="radio"] {
  margin-top: 3px;
}

.cc .navbar-form .input-append,
.navbar-form .input-prepend {
  margin-top: 6px;
  white-space: nowrap;
}

.cc .navbar-form .input-append input,
.navbar-form .input-prepend input {
  margin-top: 0;
}

.cc .navbar-search {
  position: relative;
  float: left;
  margin-top: 6px;
  margin-bottom: 0;
}

.cc .navbar-search .search-query {
  padding: 4px 9px;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 13px;
  font-weight: normal;
  line-height: 1;
  color: #ffffff;
  background-color: #626262;
  border: 1px solid #151515;
  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1), 0 1px 0 rgba(255, 255, 255, 0.15);
     -moz-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1), 0 1px 0 rgba(255, 255, 255, 0.15);
          box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1), 0 1px 0 rgba(255, 255, 255, 0.15);
  -webkit-transition: none;
     -moz-transition: none;
      -ms-transition: none;
       -o-transition: none;
          transition: none;
}

.cc .navbar-search .search-query:-moz-placeholder {
  color: #cccccc;
}

.cc .navbar-search .search-query:-ms-input-placeholder {
  color: #cccccc;
}

.cc .navbar-search .search-query::-webkit-input-placeholder {
  color: #cccccc;
}

.cc .navbar-search .search-query:focus,
.navbar-search .search-query.focused {
  padding: 5px 10px;
  color: #333333;
  text-shadow: 0 1px 0 #ffffff;
  background-color: #ffffff;
  border: 0;
  outline: 0;
  -webkit-box-shadow: 0 0 3px rgba(0, 0, 0, 0.15);
     -moz-box-shadow: 0 0 3px rgba(0, 0, 0, 0.15);
          box-shadow: 0 0 3px rgba(0, 0, 0, 0.15);
}

.cc .navbar-fixed-top,
.cc .navbar-fixed-bottom {
  position: fixed;
  right: 0;
  left: 0;
  z-index: 1030;
  margin-bottom: 0;
}

.cc .navbar-fixed-top .navbar-inner,
.navbar-fixed-bottom .navbar-inner {
  padding-right: 0;
  padding-left: 0;
  -webkit-border-radius: 0;
     -moz-border-radius: 0;
          border-radius: 0;
}

.cc .navbar-fixed-top .container,
.navbar-fixed-bottom .container {
  width: 940px;
}

.cc .navbar-fixed-top {
  top: 0;
}

.cc .navbar-fixed-bottom {
  bottom: 0;
}

.cc .navbar .nav {
  position: relative;
  left: 0;
  display: block;
  float: left;
  margin: 0 10px 0 0;
}

.cc .navbar .nav.pull-right {
  float: right;
}

.cc .navbar .nav > li {
  display: block;
  float: left;
}

.cc .navbar .nav > li > a {
  float: none;
  padding: 9px 10px 11px;
  line-height: 19px;
  color: #999999;
  text-decoration: none;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
}

.cc .navbar .btn {
  display: inline-block;
  padding: 4px 10px 4px;
  margin: 5px 5px 6px;
  line-height: 18px;
}

.cc .navbar .btn-group {
  padding: 5px 5px 6px;
  margin: 0;
}

.cc .navbar .nav > li > a:hover {
  color: #ffffff;
  text-decoration: none;
  background-color: transparent;
}

.cc .navbar .nav .active > a,
.navbar .nav .active > a:hover {
  color: #ffffff;
  text-decoration: none;
  background-color: #222222;
}

.cc .navbar .divider-vertical {
  width: 1px;
  height: 40px;
  margin: 0 9px;
  overflow: hidden;
  background-color: #222222;
  border-right: 1px solid #333333;
}

.cc .navbar .nav.pull-right {
  margin-right: 0;
  margin-left: 10px;
}

.cc .navbar .btn-navbar {
  display: none;
  float: right;
  padding: 7px 10px;
  margin-right: 5px;
  margin-left: 5px;
  background-color: #2c2c2c;
  *background-color: #222222;
  background-image: -ms-linear-gradient(top, #333333, #222222);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#333333), to(#222222));
  background-image: -webkit-linear-gradient(top, #333333, #222222);
  background-image: -o-linear-gradient(top, #333333, #222222);
  background-image: linear-gradient(top, #333333, #222222);
  background-image: -moz-linear-gradient(top, #333333, #222222);
  background-repeat: repeat-x;
  border-color: #222222 #222222 #000000;
  border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#333333', endColorstr='#222222', GradientType=0);
  filter: progid:dximagetransform.microsoft.gradient(enabled=false);
  -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 0 rgba(255, 255, 255, 0.075);
     -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 0 rgba(255, 255, 255, 0.075);
          box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.1), 0 1px 0 rgba(255, 255, 255, 0.075);
}

.cc .navbar .btn-navbar:hover,
.navbar .btn-navbar:active,
.navbar .btn-navbar.active,
.navbar .btn-navbar.disabled,
.navbar .btn-navbar[disabled] {
  background-color: #222222;
  *background-color: #151515;
}

.cc .navbar .btn-navbar:active,
.navbar .btn-navbar.active {
  background-color: #080808 \9;
}

.cc .navbar .btn-navbar .icon-bar {
  display: block;
  width: 18px;
  height: 2px;
  background-color: #f5f5f5;
  -webkit-border-radius: 1px;
     -moz-border-radius: 1px;
          border-radius: 1px;
  -webkit-box-shadow: 0 1px 0 rgba(0, 0, 0, 0.25);
     -moz-box-shadow: 0 1px 0 rgba(0, 0, 0, 0.25);
          box-shadow: 0 1px 0 rgba(0, 0, 0, 0.25);
}

.cc .btn-navbar .icon-bar + .icon-bar {
  margin-top: 3px;
}

.cc .navbar .dropdown-menu:before {
  position: absolute;
  top: -7px;
  left: 9px;
  display: inline-block;
  border-right: 7px solid transparent;
  border-bottom: 7px solid #ccc;
  border-left: 7px solid transparent;
  border-bottom-color: rgba(0, 0, 0, 0.2);
  content: '';
}

.cc .navbar .dropdown-menu:after {
  position: absolute;
  top: -6px;
  left: 10px;
  display: inline-block;
  border-right: 6px solid transparent;
  border-bottom: 6px solid #ffffff;
  border-left: 6px solid transparent;
  content: '';
}

.cc .navbar-fixed-bottom .dropdown-menu:before {
  top: auto;
  bottom: -7px;
  border-top: 7px solid #ccc;
  border-bottom: 0;
  border-top-color: rgba(0, 0, 0, 0.2);
}

.cc .navbar-fixed-bottom .dropdown-menu:after {
  top: auto;
  bottom: -6px;
  border-top: 6px solid #ffffff;
  border-bottom: 0;
}

.cc .navbar .nav li.dropdown .dropdown-toggle .caret,
.navbar .nav li.dropdown.open .caret {
  border-top-color: #ffffff;
  border-bottom-color: #ffffff;
}

.cc .navbar .nav li.dropdown.active .caret {
  opacity: 1;
  filter: alpha(opacity=100);
}

.cc .navbar .nav li.dropdown.open > .dropdown-toggle,
.navbar .nav li.dropdown.active > .dropdown-toggle,
.navbar .nav li.dropdown.open.active > .dropdown-toggle {
  background-color: transparent;
}

.cc .navbar .nav li.dropdown.active > .dropdown-toggle:hover {
  color: #ffffff;
}

.cc .navbar .pull-right .dropdown-menu,
.navbar .dropdown-menu.pull-right {
  right: 0;
  left: auto;
}

.cc .navbar .pull-right .dropdown-menu:before,
.navbar .dropdown-menu.pull-right:before {
  right: 12px;
  left: auto;
}

.cc .navbar .pull-right .dropdown-menu:after,
.navbar .dropdown-menu.pull-right:after {
  right: 13px;
  left: auto;
}

.cc .breadcrumb {
  padding: 7px 14px;
  margin: 0 0 18px;
  list-style: none;
  background-color: #fbfbfb;
  background-image: -moz-linear-gradient(top, #ffffff, #f5f5f5);
  background-image: -ms-linear-gradient(top, #ffffff, #f5f5f5);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ffffff), to(#f5f5f5));
  background-image: -webkit-linear-gradient(top, #ffffff, #f5f5f5);
  background-image: -o-linear-gradient(top, #ffffff, #f5f5f5);
  background-image: linear-gradient(top, #ffffff, #f5f5f5);
  background-repeat: repeat-x;
  border: 1px solid #ddd;
  -webkit-border-radius: 3px;
     -moz-border-radius: 3px;
          border-radius: 3px;
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#ffffff', endColorstr='#f5f5f5', GradientType=0);
  -webkit-box-shadow: inset 0 1px 0 #ffffff;
     -moz-box-shadow: inset 0 1px 0 #ffffff;
          box-shadow: inset 0 1px 0 #ffffff;
}

.cc .breadcrumb li {
  display: inline-block;
  *display: inline;
  text-shadow: 0 1px 0 #ffffff;
  *zoom: 1;
}

.cc .breadcrumb .divider {
  padding: 0 5px;
  color: #999999;
}

.cc .breadcrumb .active a {
  color: #333333;
}

.cc .pagination {
  height: 36px;
  margin: 18px 0;
}

.cc .pagination ul {
  display: inline-block;
  *display: inline;
  margin-bottom: 0;
  margin-left: 0;
  -webkit-border-radius: 3px;
     -moz-border-radius: 3px;
          border-radius: 3px;
  *zoom: 1;
  -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
     -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
          box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);
}

.cc .pagination li {
  display: inline;
}

.cc .pagination a {
  float: left;
  padding: 0 14px;
  line-height: 34px;
  text-decoration: none;
  border: 1px solid #ddd;
  border-left-width: 0;
}

.cc .pagination a:hover,
.pagination .active a {
  background-color: #f5f5f5;
}

.cc .pagination .active a {
  color: #999999;
  cursor: default;
}

.cc .pagination .disabled span,
.pagination .disabled a,
.pagination .disabled a:hover {
  color: #999999;
  cursor: default;
  background-color: transparent;
}

.cc .pagination li:first-child a {
  border-left-width: 1px;
  -webkit-border-radius: 3px 0 0 3px;
     -moz-border-radius: 3px 0 0 3px;
          border-radius: 3px 0 0 3px;
}

.cc .pagination li:last-child a {
  -webkit-border-radius: 0 3px 3px 0;
     -moz-border-radius: 0 3px 3px 0;
          border-radius: 0 3px 3px 0;
}

.cc .pagination-centered {
  text-align: center;
}

.cc .pagination-right {
  text-align: right;
}

.cc .pager {
  margin-bottom: 18px;
  margin-left: 0;
  text-align: center;
  list-style: none;
  *zoom: 1;
}

.cc .pager:before,
.cc .pager:after {
  display: table;
  content: "";
}

.cc .pager:after {
  clear: both;
}

.cc .pager li {
  display: inline;
}

.cc .pager a {
  display: inline-block;
  padding: 5px 14px;
  background-color: #fff;
  border: 1px solid #ddd;
  -webkit-border-radius: 15px;
     -moz-border-radius: 15px;
          border-radius: 15px;
}

.cc .pager a:hover {
  text-decoration: none;
  background-color: #f5f5f5;
}

.cc .pager .next a {
  float: right;
}

.cc .pager .previous a {
  float: left;
}

.cc .pager .disabled a,
.pager .disabled a:hover {
  color: #999999;
  cursor: default;
  background-color: #fff;
}

.cc .modal-open .dropdown-menu {
  z-index: 2050;
}

.cc .modal-open .dropdown.open {
  *z-index: 2050;
}

.cc .modal-open .popover {
  z-index: 2060;
}

.cc .modal-open .tooltip {
  z-index: 2070;
}

.cc .modal-backdrop {
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 1040;
  background-color: #000000;
}

.cc .modal-backdrop.fade {
  opacity: 0;
}

.cc .modal-backdrop,
.cc .modal-backdrop.fade.in {
  opacity: 0.8;
  filter: alpha(opacity=80);
}

.cc .modal {
  position: fixed;
  top: 50%;
  left: 50%;
  z-index: 1050;
  width: 560px;
  margin: -250px 0 0 -280px;
  overflow: auto;
  background-color: #ffffff;
  border: 1px solid #999;
  border: 1px solid rgba(0, 0, 0, 0.3);
  *border: 1px solid #999;
  -webkit-border-radius: 6px;
     -moz-border-radius: 6px;
          border-radius: 6px;
  -webkit-box-shadow: 0 3px 7px rgba(0, 0, 0, 0.3);
     -moz-box-shadow: 0 3px 7px rgba(0, 0, 0, 0.3);
          box-shadow: 0 3px 7px rgba(0, 0, 0, 0.3);
  -webkit-background-clip: padding-box;
     -moz-background-clip: padding-box;
          background-clip: padding-box;
}

.cc .modal.fade {
  top: -25%;
  -webkit-transition: opacity 0.3s linear, top 0.3s ease-out;
     -moz-transition: opacity 0.3s linear, top 0.3s ease-out;
      -ms-transition: opacity 0.3s linear, top 0.3s ease-out;
       -o-transition: opacity 0.3s linear, top 0.3s ease-out;
          transition: opacity 0.3s linear, top 0.3s ease-out;
}

.cc .modal.fade.in {
  top: 50%;
}

.cc .modal-header {
  padding: 9px 15px;
  border-bottom: 1px solid #eee;
}

.cc .modal-header .close {
  margin-top: 2px;
}

.cc .modal-body {
  max-height: 400px;
  padding: 15px;
  overflow-y: auto;
}

.cc .modal-form {
  margin-bottom: 0;
}

.cc .modal-footer {
  padding: 14px 15px 15px;
  margin-bottom: 0;
  text-align: right;
  background-color: #f5f5f5;
  border-top: 1px solid #ddd;
  -webkit-border-radius: 0 0 6px 6px;
     -moz-border-radius: 0 0 6px 6px;
          border-radius: 0 0 6px 6px;
  *zoom: 1;
  -webkit-box-shadow: inset 0 1px 0 #ffffff;
     -moz-box-shadow: inset 0 1px 0 #ffffff;
          box-shadow: inset 0 1px 0 #ffffff;
}

.cc .modal-footer:before,
.cc .modal-footer:after {
  display: table;
  content: "";
}

.cc .modal-footer:after {
  clear: both;
}

.cc .modal-footer .btn + .btn {
  margin-bottom: 0;
  margin-left: 5px;
}

.cc .modal-footer .btn-group .btn + .btn {
  margin-left: -1px;
}

.cc .tooltip {
  position: absolute;
  z-index: 1020;
  display: block;
  padding: 5px;
  font-size: 11px;
  opacity: 0;
  filter: alpha(opacity=0);
  visibility: visible;
}

.cc .tooltip.in {
  opacity: 0.8;
  filter: alpha(opacity=80);
}

.cc .tooltip.top {
  margin-top: -2px;
}

.cc .tooltip.right {
  margin-left: 2px;
}

.cc .tooltip.bottom {
  margin-top: 2px;
}

.cc .tooltip.left {
  margin-left: -2px;
}

.cc .tooltip.top .tooltip-arrow {
  bottom: 0;
  left: 50%;
  margin-left: -5px;
  border-top: 5px solid #000000;
  border-right: 5px solid transparent;
  border-left: 5px solid transparent;
}

.cc .tooltip.left .tooltip-arrow {
  top: 50%;
  right: 0;
  margin-top: -5px;
  border-top: 5px solid transparent;
  border-bottom: 5px solid transparent;
  border-left: 5px solid #000000;
}

.cc .tooltip.bottom .tooltip-arrow {
  top: 0;
  left: 50%;
  margin-left: -5px;
  border-right: 5px solid transparent;
  border-bottom: 5px solid #000000;
  border-left: 5px solid transparent;
}

.cc .tooltip.right .tooltip-arrow {
  top: 50%;
  left: 0;
  margin-top: -5px;
  border-top: 5px solid transparent;
  border-right: 5px solid #000000;
  border-bottom: 5px solid transparent;
}

.cc .tooltip-inner {
  max-width: 200px;
  padding: 3px 8px;
  color: #ffffff;
  text-align: center;
  text-decoration: none;
  background-color: #000000;
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
}

.cc .tooltip-arrow {
  position: absolute;
  width: 0;
  height: 0;
}

.cc .popover {
  position: absolute;
  top: 0;
  left: 0;
  z-index: 1010;
  display: none;
  padding: 5px;
}

.cc .popover.top {
  margin-top: -5px;
}

.cc .popover.right {
  margin-left: 5px;
}

.cc .popover.bottom {
  margin-top: 5px;
}

.cc .popover.left {
  margin-left: -5px;
}

.cc .popover.top .arrow {
  bottom: 0;
  left: 50%;
  margin-left: -5px;
  border-top: 5px solid #000000;
  border-right: 5px solid transparent;
  border-left: 5px solid transparent;
}

.cc .popover.right .arrow {
  top: 50%;
  left: 0;
  margin-top: -5px;
  border-top: 5px solid transparent;
  border-right: 5px solid #000000;
  border-bottom: 5px solid transparent;
}

.cc .popover.bottom .arrow {
  top: 0;
  left: 50%;
  margin-left: -5px;
  border-right: 5px solid transparent;
  border-bottom: 5px solid #000000;
  border-left: 5px solid transparent;
}

.cc .popover.left .arrow {
  top: 50%;
  right: 0;
  margin-top: -5px;
  border-top: 5px solid transparent;
  border-bottom: 5px solid transparent;
  border-left: 5px solid #000000;
}

.cc .popover .arrow {
  position: absolute;
  width: 0;
  height: 0;
}

.cc .popover-inner {
  width: 280px;
  padding: 3px;
  overflow: hidden;
  background: #000000;
  background: rgba(0, 0, 0, 0.8);
  -webkit-border-radius: 6px;
     -moz-border-radius: 6px;
          border-radius: 6px;
  -webkit-box-shadow: 0 3px 7px rgba(0, 0, 0, 0.3);
     -moz-box-shadow: 0 3px 7px rgba(0, 0, 0, 0.3);
          box-shadow: 0 3px 7px rgba(0, 0, 0, 0.3);
}

.cc .popover-title {
  padding: 9px 15px;
  line-height: 1;
  background-color: #f5f5f5;
  border-bottom: 1px solid #eee;
  -webkit-border-radius: 3px 3px 0 0;
     -moz-border-radius: 3px 3px 0 0;
          border-radius: 3px 3px 0 0;
}

.cc .popover-content {
  padding: 14px;
  background-color: #ffffff;
  -webkit-border-radius: 0 0 3px 3px;
     -moz-border-radius: 0 0 3px 3px;
          border-radius: 0 0 3px 3px;
  -webkit-background-clip: padding-box;
     -moz-background-clip: padding-box;
          background-clip: padding-box;
}

.cc .popover-content p,
.popover-content ul,
.popover-content ol {
  margin-bottom: 0;
}

.cc .thumbnails {
  margin-left: -20px;
  list-style: none;
  *zoom: 1;
}

.cc .thumbnails:before,
.cc .thumbnails:after {
  display: table;
  content: "";
}

.cc .thumbnails:after {
  clear: both;
}

.cc .row-fluid .thumbnails {
  margin-left: 0;
}

.cc .thumbnails > li {
  float: left;
  margin-bottom: 18px;
  margin-left: 20px;
}

.cc .thumbnail {
  display: block;
  padding: 4px;
  line-height: 1;
  border: 1px solid #ddd;
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
  -webkit-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075);
     -moz-box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075);
          box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075);
}

.cc a.thumbnail:hover {
  border-color: #0088cc;
  -webkit-box-shadow: 0 1px 4px rgba(0, 105, 214, 0.25);
     -moz-box-shadow: 0 1px 4px rgba(0, 105, 214, 0.25);
          box-shadow: 0 1px 4px rgba(0, 105, 214, 0.25);
}

.cc .thumbnail > img {
  display: block;
  max-width: 100%;
  margin-right: auto;
  margin-left: auto;
}

.cc .thumbnail .caption {
  padding: 9px;
}

.cc .label,
.cc .badge {
  font-size: 10.998px;
  font-weight: bold;
  line-height: 14px;
  color: #ffffff;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
  white-space: nowrap;
  vertical-align: baseline;
  background-color: #999999;
}

.cc .label {
  padding: 1px 4px 2px;
  -webkit-border-radius: 3px;
     -moz-border-radius: 3px;
          border-radius: 3px;
}

.cc .badge {
  padding: 1px 9px 2px;
  -webkit-border-radius: 9px;
     -moz-border-radius: 9px;
          border-radius: 9px;
}

.cc a.label:hover,
.cc a.badge:hover {
  color: #ffffff;
  text-decoration: none;
  cursor: pointer;
}

.cc .label-important,
.cc .badge-important {
  background-color: #b94a48;
}

.cc .label-important[href],
.cc .badge-important[href] {
  background-color: #953b39;
}

.cc .label-warning,
.cc .badge-warning {
  background-color: #f89406;
}

.cc .label-warning[href],
.cc .badge-warning[href] {
  background-color: #c67605;
}

.cc .label-success,
.cc .badge-success {
  background-color: #468847;
}

.cc .label-success[href],
.cc .badge-success[href] {
  background-color: #356635;
}

.cc .label-info,
.cc .badge-info {
  background-color: #3a87ad;
}

.cc .label-info[href],
.cc .badge-info[href] {
  background-color: #2d6987;
}

.cc .label-inverse,
.cc .badge-inverse {
  background-color: #333333;
}

.cc .label-inverse[href],
.cc .badge-inverse[href] {
  background-color: #1a1a1a;
}

.cc @-webkit-keyframes progress-bar-stripes {
  from {
    background-position: 40px 0;
  }
  to {
    background-position: 0 0;
  }
}

.cc @-moz-keyframes progress-bar-stripes {
  from {
    background-position: 40px 0;
  }
  to {
    background-position: 0 0;
  }
}

.cc @-ms-keyframes progress-bar-stripes {
  from {
    background-position: 40px 0;
  }
  to {
    background-position: 0 0;
  }
}

.cc @-o-keyframes progress-bar-stripes {
  from {
    background-position: 0 0;
  }
  to {
    background-position: 40px 0;
  }
}

.cc @keyframes progress-bar-stripes {
  from {
    background-position: 40px 0;
  }
  to {
    background-position: 0 0;
  }
}

.cc .progress {
  height: 18px;
  margin-bottom: 18px;
  overflow: hidden;
  background-color: #f7f7f7;
  background-image: -moz-linear-gradient(top, #f5f5f5, #f9f9f9);
  background-image: -ms-linear-gradient(top, #f5f5f5, #f9f9f9);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#f5f5f5), to(#f9f9f9));
  background-image: -webkit-linear-gradient(top, #f5f5f5, #f9f9f9);
  background-image: -o-linear-gradient(top, #f5f5f5, #f9f9f9);
  background-image: linear-gradient(top, #f5f5f5, #f9f9f9);
  background-repeat: repeat-x;
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#f5f5f5', endColorstr='#f9f9f9', GradientType=0);
  -webkit-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
     -moz-box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
          box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.1);
}

.cc .progress .bar {
  width: 0;
  height: 18px;
  font-size: 12px;
  color: #ffffff;
  text-align: center;
  text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25);
  background-color: #0e90d2;
  background-image: -moz-linear-gradient(top, #149bdf, #0480be);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#149bdf), to(#0480be));
  background-image: -webkit-linear-gradient(top, #149bdf, #0480be);
  background-image: -o-linear-gradient(top, #149bdf, #0480be);
  background-image: linear-gradient(top, #149bdf, #0480be);
  background-image: -ms-linear-gradient(top, #149bdf, #0480be);
  background-repeat: repeat-x;
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#149bdf', endColorstr='#0480be', GradientType=0);
  -webkit-box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
     -moz-box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
          box-shadow: inset 0 -1px 0 rgba(0, 0, 0, 0.15);
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
      -ms-box-sizing: border-box;
          box-sizing: border-box;
  -webkit-transition: width 0.6s ease;
     -moz-transition: width 0.6s ease;
      -ms-transition: width 0.6s ease;
       -o-transition: width 0.6s ease;
          transition: width 0.6s ease;
}

.cc .progress-striped .bar {
  background-color: #149bdf;
  background-image: -o-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -webkit-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -moz-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -ms-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -webkit-gradient(linear, 0 100%, 100% 0, color-stop(0.25, rgba(255, 255, 255, 0.15)), color-stop(0.25, transparent), color-stop(0.5, transparent), color-stop(0.5, rgba(255, 255, 255, 0.15)), color-stop(0.75, rgba(255, 255, 255, 0.15)), color-stop(0.75, transparent), to(transparent));
  background-image: linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  -webkit-background-size: 40px 40px;
     -moz-background-size: 40px 40px;
       -o-background-size: 40px 40px;
          background-size: 40px 40px;
}

.cc .progress.active .bar {
  -webkit-animation: progress-bar-stripes 2s linear infinite;
     -moz-animation: progress-bar-stripes 2s linear infinite;
      -ms-animation: progress-bar-stripes 2s linear infinite;
       -o-animation: progress-bar-stripes 2s linear infinite;
          animation: progress-bar-stripes 2s linear infinite;
}

.cc .progress-danger .bar {
  background-color: #dd514c;
  background-image: -moz-linear-gradient(top, #ee5f5b, #c43c35);
  background-image: -ms-linear-gradient(top, #ee5f5b, #c43c35);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ee5f5b), to(#c43c35));
  background-image: -webkit-linear-gradient(top, #ee5f5b, #c43c35);
  background-image: -o-linear-gradient(top, #ee5f5b, #c43c35);
  background-image: linear-gradient(top, #ee5f5b, #c43c35);
  background-repeat: repeat-x;
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#ee5f5b', endColorstr='#c43c35', GradientType=0);
}

.cc .progress-danger.progress-striped .bar {
  background-color: #ee5f5b;
  background-image: -webkit-gradient(linear, 0 100%, 100% 0, color-stop(0.25, rgba(255, 255, 255, 0.15)), color-stop(0.25, transparent), color-stop(0.5, transparent), color-stop(0.5, rgba(255, 255, 255, 0.15)), color-stop(0.75, rgba(255, 255, 255, 0.15)), color-stop(0.75, transparent), to(transparent));
  background-image: -webkit-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -moz-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -ms-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
}

.cc .progress-success .bar {
  background-color: #5eb95e;
  background-image: -moz-linear-gradient(top, #62c462, #57a957);
  background-image: -ms-linear-gradient(top, #62c462, #57a957);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#62c462), to(#57a957));
  background-image: -webkit-linear-gradient(top, #62c462, #57a957);
  background-image: -o-linear-gradient(top, #62c462, #57a957);
  background-image: linear-gradient(top, #62c462, #57a957);
  background-repeat: repeat-x;
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#62c462', endColorstr='#57a957', GradientType=0);
}

.cc .progress-success.progress-striped .bar {
  background-color: #62c462;
  background-image: -webkit-gradient(linear, 0 100%, 100% 0, color-stop(0.25, rgba(255, 255, 255, 0.15)), color-stop(0.25, transparent), color-stop(0.5, transparent), color-stop(0.5, rgba(255, 255, 255, 0.15)), color-stop(0.75, rgba(255, 255, 255, 0.15)), color-stop(0.75, transparent), to(transparent));
  background-image: -webkit-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -moz-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -ms-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
}

.cc .progress-info .bar {
  background-color: #4bb1cf;
  background-image: -moz-linear-gradient(top, #5bc0de, #339bb9);
  background-image: -ms-linear-gradient(top, #5bc0de, #339bb9);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#5bc0de), to(#339bb9));
  background-image: -webkit-linear-gradient(top, #5bc0de, #339bb9);
  background-image: -o-linear-gradient(top, #5bc0de, #339bb9);
  background-image: linear-gradient(top, #5bc0de, #339bb9);
  background-repeat: repeat-x;
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#5bc0de', endColorstr='#339bb9', GradientType=0);
}

.cc .progress-info.progress-striped .bar {
  background-color: #5bc0de;
  background-image: -webkit-gradient(linear, 0 100%, 100% 0, color-stop(0.25, rgba(255, 255, 255, 0.15)), color-stop(0.25, transparent), color-stop(0.5, transparent), color-stop(0.5, rgba(255, 255, 255, 0.15)), color-stop(0.75, rgba(255, 255, 255, 0.15)), color-stop(0.75, transparent), to(transparent));
  background-image: -webkit-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -moz-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -ms-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
}

.cc .progress-warning .bar {
  background-color: #faa732;
  background-image: -moz-linear-gradient(top, #fbb450, #f89406);
  background-image: -ms-linear-gradient(top, #fbb450, #f89406);
  background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#fbb450), to(#f89406));
  background-image: -webkit-linear-gradient(top, #fbb450, #f89406);
  background-image: -o-linear-gradient(top, #fbb450, #f89406);
  background-image: linear-gradient(top, #fbb450, #f89406);
  background-repeat: repeat-x;
  filter: progid:dximagetransform.microsoft.gradient(startColorstr='#fbb450', endColorstr='#f89406', GradientType=0);
}

.cc .progress-warning.progress-striped .bar {
  background-color: #fbb450;
  background-image: -webkit-gradient(linear, 0 100%, 100% 0, color-stop(0.25, rgba(255, 255, 255, 0.15)), color-stop(0.25, transparent), color-stop(0.5, transparent), color-stop(0.5, rgba(255, 255, 255, 0.15)), color-stop(0.75, rgba(255, 255, 255, 0.15)), color-stop(0.75, transparent), to(transparent));
  background-image: -webkit-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -moz-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -ms-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: -o-linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
  background-image: linear-gradient(-45deg, rgba(255, 255, 255, 0.15) 25%, transparent 25%, transparent 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, transparent 75%, transparent);
}

.cc .accordion {
  margin-bottom: 18px;
}

.cc .accordion-group {
  margin-bottom: 2px;
  border: 1px solid #e5e5e5;
  -webkit-border-radius: 4px;
     -moz-border-radius: 4px;
          border-radius: 4px;
}

.cc .accordion-heading {
  border-bottom: 0;
}

.cc .accordion-heading .accordion-toggle {
  display: block;
  padding: 8px 15px;
}

.cc .accordion-toggle {
  cursor: pointer;
}

.cc .accordion-inner {
  padding: 9px 15px;
  border-top: 1px solid #e5e5e5;
}

.cc .carousel {
  position: relative;
  margin-bottom: 18px;
  line-height: 1;
}

.cc .carousel-inner {
  position: relative;
  width: 100%;
  overflow: hidden;
}

.cc .carousel .item {
  position: relative;
  display: none;
  -webkit-transition: 0.6s ease-in-out left;
     -moz-transition: 0.6s ease-in-out left;
      -ms-transition: 0.6s ease-in-out left;
       -o-transition: 0.6s ease-in-out left;
          transition: 0.6s ease-in-out left;
}

.cc .carousel .item > img {
  display: block;
  line-height: 1;
}

.cc .carousel .active,
.carousel .next,
.carousel .prev {
  display: block;
}

.cc .carousel .active {
  left: 0;
}

.cc .carousel .next,
.carousel .prev {
  position: absolute;
  top: 0;
  width: 100%;
}

.cc .carousel .next {
  left: 100%;
}

.cc .carousel .prev {
  left: -100%;
}

.cc .carousel .next.left,
.carousel .prev.right {
  left: 0;
}

.cc .carousel .active.left {
  left: -100%;
}

.cc .carousel .active.right {
  left: 100%;
}

.cc .carousel-control {
  position: absolute;
  top: 40%;
  left: 15px;
  width: 40px;
  height: 40px;
  margin-top: -20px;
  font-size: 60px;
  font-weight: 100;
  line-height: 30px;
  color: #ffffff;
  text-align: center;
  background: #222222;
  border: 3px solid #ffffff;
  -webkit-border-radius: 23px;
     -moz-border-radius: 23px;
          border-radius: 23px;
  opacity: 0.5;
  filter: alpha(opacity=50);
}

.cc .carousel-control.right {
  right: 15px;
  left: auto;
}

.cc .carousel-control:hover {
  color: #ffffff;
  text-decoration: none;
  opacity: 0.9;
  filter: alpha(opacity=90);
}

.cc .carousel-caption {
  position: absolute;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 10px 15px 5px;
  background: #333333;
  background: rgba(0, 0, 0, 0.75);
}

.cc .carousel-caption h4,
.carousel-caption p {
  color: #ffffff;
}

.cc .hero-unit {
  padding: 60px;
  margin-bottom: 30px;
  background-color: #eeeeee;
  -webkit-border-radius: 6px;
     -moz-border-radius: 6px;
          border-radius: 6px;
}

.cc .hero-unit h1 {
  margin-bottom: 0;
  font-size: 60px;
  line-height: 1;
  letter-spacing: -1px;
  color: inherit;
}

.cc .hero-unit p {
  font-size: 18px;
  font-weight: 200;
  line-height: 27px;
  color: inherit;
}

.cc .pull-right {
  float: right;
}

.cc .pull-left {
  float: left;
}

.cc .hide {
  display: none;
}

.cc .show {
  display: block;
}

.cc .invisible {
  visibility: hidden;
}